### ISSUE TITLE
AttributeError: 'numpy.bool_' object has no attribute 'variables'

### ISSUE THREAD

**Issue by minkkkk** [cvxgrp/cvxpy#600] opened 2018-10-11 00:25 UTC
I am new to cvxpy and modelling the optimization problem. I followed the basic example "control" and developed my coding example but there's an error. Please give me answer to figure out this problem.. 

Traceback (most recent call last):
  File "C:\Users\soyeon\Desktop\2018 Fall\test1006.py", line 111, in <module>
    prob = cvx.Problem(cvx.Minimize(objective), constrlist)
  File "C:\Users\soyeon\Miniconda3\lib\site-packages\cvxpy\problems\problem.py", line 78, in __init__
    self._size_metrics = SizeMetrics(self)
  File "C:\Users\soyeon\Miniconda3\lib\site-packages\cvxpy\problems\problem.py", line 672, in __init__
    for var in problem.variables():
  File "C:\Users\soyeon\Miniconda3\lib\site-packages\cvxpy\problems\problem.py", line 145, in variables
    vars_ += constr.variables()
AttributeError: 'numpy.bool_' object has no attribute 'variables'

**Comment by akshayka** [comment] 2018-10-16 03:10
The stack trace makes it seem like the issue is with your code, not CVXPY. In particular, it indicates that one of your constraints in constrlist is a NumPy object. As such, I’m closing this issue.

Feel free to post this question (along with your source code) on StackOverflow. If you tage the question with “cvxpy”, you should receive a response.

**Closed by akshayka** 2018-10-16 03:10 UTC
