### ISSUE TITLE
Unreliable QP canonicalization

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#591] opened 2018-10-02 02:59 UTC
At the moment there are many issues with the QP canonicalization. There are 

- wrong dual variables (see example below): Fix in https://github.com/cvxgrp/cvxpy/pull/596
- unnecessary extra variables introduced #476: Fix in 627f1c9313f7fd1201a
- badly conditioned problems #580

As @rileyjmurray mentioned, this issue should be solved as soon as possible since it makes the whole 1.0 parsing unreliable at the moment. I believe @roversch @akshayka made most of the new canonicalization.

Below there is an example where the intro QP in the docs gives the wrong dual variables.

Script
```python
import cvxpy as cp
import numpy as np

# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.sum_squares(A*x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve(solver=cp.OSQP,
                                 eps_abs=1e-08, eps_rel=1e-08,
                                 verbose=True)
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print("dual of >= 0 ", constraints[0].dual_value)
print("dual of <= 1 ", constraints[1].dual_value)
```
Results
```
dual of x >= 0  [ 1.11456252 -1.03217382  2.2772236   0.94498967  4.02388116  0.67026535
  0.27776185  2.06385093  1.36350625 -2.5493355   0.28801915 -1.02375817
 -1.12508898  1.29454151  3.16203528  1.54534733 -1.0378457   1.41727883
 -0.88600972  0.31479474]
dual of x <= 1  [ 0.72037306  3.22356912 -1.14380032  0.67797671 -2.00098996 -0.50103141
  0.70177845 -1.70737085 -0.06671662  0.910168    2.50938945  0.
  2.78354615  1.79425782 13.08579183  0.          0.73716363  3.35344995
  0.          0.        ]
```
Note that OSQP in this script runs with high precision and polishing is successful. The same results appear with GUROBI. If I run the same script with MOSEK (with the conic formulation) the dual variables have the correct signs
```
dual of x >= 0  [ 2.50938787e+00  1.37950910e-07  2.78354503e+00  1.79424607e+00
  1.30857890e+01  1.72411040e-08  7.37146966e-01  3.35345061e+00
  8.08215261e-09 -3.48595918e-10  8.93825046e+00  3.05652262e-06
  7.02955038e+00  9.56192274e-09  4.71068332e+00  3.18873795e+00
  2.06088746e+00  1.00816720e+01  3.04810831e+00  8.53267117e+00]
dual of x <= 1  [-3.01585879e-09  4.79738849e-10  3.82103188e-10  3.47231199e-10
 -2.97204255e-09 -2.33638665e-09 -3.03446592e-09 -3.00354179e-09
 -1.78720801e-09  2.16170835e-09  3.56771535e-10 -3.03193172e-09
 -3.00603149e-09 -1.94916203e-09 -3.01172075e-09 -3.00868925e-09
 -3.00399861e-09 -3.00492616e-09 -2.99928696e-09 -3.01734409e-09]
```
This dual variables issue appeared in #588 but it does not seem related to the OSQP precision. It is an issue with the QP canonicalization.

**Comment by rileyjmurray** [comment] 2018-10-02 03:52
EOCS likewise returns a valid dual variable. So I agree that the issue is in QP canonicalization.

**Comment by gbanjac** [comment] 2018-10-02 20:10
Not only the signs are wrong, but the complementary slackness is not satisfied either.

**Comment by rileyjmurray** [comment] 2018-10-04 16:36
@SteveDiamond I think this should be at the top of our list for development effort right now. Pinging @enzobusseti @moehle @takapoui -- the three of you worked on QP canonicalization features, yes?

**Comment by bstellato** [comment] 2018-10-04 17:12
I believe the QP canonicalization is at the moment quite problematic. This is possible related to issues #580 and #476.

Also @akshayka and @roversch worked on the QP canonicalization and cvxpy 1.0.

**Comment by akshayka** [comment] 2018-10-04 17:22
I worked on 1.0, but I can’t take credit for QP canonicalization; @roversch worked on that with input from @stevediamond.

**Comment by enzobusseti** [comment] 2018-10-04 17:35
(I’m referring to the work on this branch: https://github.com/cvxgrp/cvxpy/commits/qp_parsing_compiling <https://github.com/cvxgrp/cvxpy/commits/qp_parsing_compiling> , whose last commit date is quite infamous…)

**Comment by gbanjac** [comment] 2018-10-09 09:17
For the problem above, OSQP solves the problem correctly, but there is a bug in the [`invert`](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py#L31-L54) function when assigning optimal Lagrange multipliers to different constraints.

CVXPY introduces an additional constraint of the form `A*x - s == b` so a part of the optimal dual variable returned by OSQP is related to this constraint.

I tried a hack in which I flipped the order of equality and inequality constraints in [OSQP](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py#L61-L65), [GUROBI](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py#L126-L148) and [CPLEX](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py#L125-L142), and it seems that the problem is gone.

The hack is based on the fact that the `sorted_constraints` object is used [for assigning the dual variables](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py#L46) to different constraints, which is constructed [here](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/qp_solver.py#L111) by concatenating inequality and equality constraints (in this order).

I am not sure if this is the right way to solve the issue. Maybe the bug should be fixed in a more systematic way.

**Comment by bstellato** [comment] 2018-10-09 14:02
Thanks a lot for this. I made a PR with that simple fix. At least the dual variables seem to be working now. The other issues remain open.

**Comment by bstellato** [comment] 2018-10-09 14:32
It looks like the `sum_squares` atom is creating some issues. I see that in the standard canonicalization is just a wrapper to `quad_over_lin` with the linear part begin 1. 

https://github.com/cvxgrp/cvxpy/blob/941b1caf04dc16824e7d49fb2343eb70803c2c7e/cvxpy/atoms/sum_squares.py#L33

This happens also in the QP canonicalization but it is completely unnecessary and it creates a new variable `t`. See 

https://github.com/cvxgrp/cvxpy/blob/941b1caf04dc16824e7d49fb2343eb70803c2c7e/cvxpy/reductions/qp2quad_form/atom_canonicalizers/quad_over_lin_canon.py#L22-L26

@SteveDiamond @roversch Is there a reason why it is written in this way? Can't we just create a `sum_squares` atom that converts the expression to a `quad_form`?

**Comment by SteveDiamond** [comment] 2018-10-09 23:34
I removed extraneous variables as suggested by @bstellato. More generally, one issue is that the CoeffExtractor class which merges all the quadratic forms together assumes the quad_forms have Variables as arguments. Handling arbitrary affine expressions may be advantageous. In general though the philosophy of cvxpy is to create more variables if it simplifies canonicalization.

@enzobusseti The first part of the canonicalization of QPs is the same as you and Nick worked out. There is a second stage that converts the symbolic QP into a QP with materialized matrices.

I don't know what the issue is with the ill conditioned example. It will take more investigation.

**Comment by bstellato** [comment] 2018-10-11 14:16
Thanks @SteveDiamond for making the changes. As @gbanjac said, the bad scaling is an issue of the control example  and not of the parsing https://github.com/cvxgrp/cvxpy/issues/580#issuecomment-428491972. I will close this issue since all the problems seem to be fixed now.

**Closed** 2018-10-11 14:16 UTC
