### ISSUE TITLE
DGPError when variable has zero coefficient

### ISSUE THREAD

**Issue by KevinDalySmith** [cvxgrp/cvxpy#1281] opened 2021-03-15 01:35 UTC
Multiplying any decision variable by zero results in an error message when trying to solve a geometric program. For example, the code
```
import cvxpy as cp
x = cp.Variable(2, pos=True)
problem = cp.Problem(
    cp.Minimize(x[0] * x[1]),
    [0 * x[0] + x[1] <= 1])
problem.solve(gp=True)
```
results in the following DGPError message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 436, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 919, in _solve
    solver, gp, enforce_dpp, verbose)
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 543, in get_problem_data
    solver=solver, gp=gp, enforce_dpp=enforce_dpp)
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 772, in _construct_chain
    enforce_dpp=enforce_dpp)
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 152, in construct_solving_chain
    reductions = _reductions_for_problem_class(problem, candidates, gp)
  File "C:\tools\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 100, in _reductions_for_problem_class
    raise DGPError("Problem does not follow DGP rules." + append)
cvxpy.error.DGPError: Problem does not follow DGP rules.The following constraints are not DGP:
```
Of course, replacing the constraint ```0 * x[0] + x[1] <= 1``` with ```x[1] <= 1``` fixes the problem, but it would be convenient to be able enter more complex constraints via operations with sparse matrices without this error coming up. 

(I am running cvxpy version 1.1.11, Python 3.7.4, and Windows 10.)

**Comment by rileyjmurray** [comment] 2021-03-15 22:05
Thanks for the report @KevinDalySmith. However, since this is a duplicate of #1153, I'll close this issue.

**Closed by rileyjmurray** 2021-03-15 22:05 UTC
