### ISSUE TITLE
std::length_error with variable size 1527x1527

### ISSUE THREAD

**Issue by Aakriti05** [cvxgrp/cvxpy#741] opened 2019-06-02 17:03 UTC
I am trying to run the following code (attached below). It works with img_len = 1000. But it gives me the following error when trying to run with img_len = 1527. Can anyone give me an idea of what could the problem be? Is there a matrix size constraint somewhere?

```
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
Aborted (core dumped)
```
 

```
img_len = 1527
Z = cp.Variable(shape=(img_len,img_len))
one = np.ones([img_len,img_len])

objective = cp.Minimize(cp.pnorm(Z,2) + cp.trace(Z))
constraints = [0 <= Z, one.transpose()*Z == one.transpose()]
prob = cp.Problem(objective, constraints)
result = prob.solve("SCS", gpu=True, verbose=True)
```

**Comment by akshayka** [comment] 2019-06-02 18:11
Definitely a bug. Thanks for reporting; we'll look into it.

**Comment by akshayka** [comment] 2019-06-02 18:17
Did a tiny bit of snooping, and the error is thrown in cvxcore. Line 716 of LinOpOperations.cpp, in `get_mul_mat`: ` tripletList.reserve(num_blocks * block.nonZeros())` attempts to reserve too much memory. I don't have time to look into this today, but if anyone else has time: a next step for debugging would be to insert print statements around this line to observe, e.g. the size of `tripletList`, `num_blocks`, and `block.nonZeros()`.

**Comment by SteveDiamond** [comment] 2019-06-02 18:33
``cp.pnorm(Z,2)`` is a matrix norm. Perhaps you meant ``cp.pnorm(Z,'fro')``? If not, the problem will be too large to solve.

**Comment by Aakriti05** [comment] 2019-06-02 21:48
@SteveDiamond ... I believe you meant to say cp.norm(Z, 'fro') as pnorm() do not have 'fro' option. I tried with cp.norm(Z, 'fro'), but still of no use.

**Comment by akshayka** [comment] 2019-06-03 04:39
@SteveDiamond , I'm not sure why, but it's the `matmul` that's causing the error. When the second constraint (which involves the matmul) is removed, the script runs successfully. 

Here's a minimal example:

```
import cvxpy as cp
import numpy as np


img_len = 1527
Z = cp.Variable(shape=(img_len,img_len))
one = np.ones([img_len,img_len])
objective = cp.Minimize(0)
constraints = [one @ Z == one]
prob = cp.Problem(objective, constraints)
result = prob.get_problem_data(solver=cp.SCS)
```

**Comment by SteveDiamond** [comment] 2019-06-03 04:45
Yeah, my diagnosis was completely off, I was thinking of norm and not pnorm. Matrix-matrix multiplies get expanded massively during canonicalization. There's no way around it, short of special solvers.

**Comment by akshayka** [comment] 2019-06-03 04:47
@Aakriti05 , if the code snippet you pasted is actually what you want to solve, you can work around this issue for now by replacing your second constraint with `cp.sum(Z, axis=0) == 1`, which will enforce the column sums of `Z` to equal `1`.

**Comment by Aakriti05** [comment] 2019-06-03 13:08
@akshayka ... Thanks for your reply. Changing the constraint to cp.sum() works with the above objective. But in my actual objective function, I need to multiply Z with matrices C and D which are of the same size as Z i.e. 1527x1527. 

`objective = cp.Minimize(cp.pnorm(C*Z,2) + cp.trace(D*Z))`

It throws the same error as above, probably due to matrix multiplication as suggested by you. Do you know what I should do in this case?

**Comment by rileyjmurray** [comment] 2019-06-04 15:25
@SteveDiamond , could you expand on " Matrix-matrix multiplies get expanded massively during canonicalization. There's no way around it, short of special solvers." ? 

Maybe this is a good place to start for the matrix-chain-multiplication mentioned in #708 ?

**Comment by SteveDiamond** [comment] 2019-06-04 22:05
Sure, in the example above ``C*Z`` gets expanded into a block diagonal matrix
```
---------
C
  C
     \
       C
---------
```
with one instance of ``C`` for each column of ``Z``. This is unavoidable, because it's the way the problem needs to be expressed for a cone program solver. There are special solvers for problems with this structure that will use more efficient representations of the matrix (MPC solvers are one example).

**Comment by rileyjmurray** [comment] 2019-06-05 01:10
@SteveDiamond  Ah I see. Yes that transformation is very standard and can only be avoided if a solver allows for very special standard forms.

@Aakriti05 it seems like this is essentially an out-of-memory error. How much RAM does your machine have?

**Comment by Aakriti05** [comment] 2019-06-06 12:35
@rileyjmurray .. I have tried on two systems with 94G and 136G of RAM respectively. It worked only till the matrix size 1100x1100 in both the systems.

**Comment by rileyjmurray** [comment] 2019-06-06 15:14
I see. Your machines should be able to solve these problems then. The issue is likely just with allocating all that memory *at once*. I have short-term advice for your problem, and longer term remarks for @SteveDiamond.

For your problem, introduce an auxilliary variable ``W = cvxpy.Variable(shape=(img_len, img_len))``, with constraints ``cons = [ W[:, i] == C @ Z[:, i] for i in range(img_len)]``. Then include a term ``expr1 = cvxpy.pnorm(W,2)`` in the objective. For the trace term, I recommend only computing the matrix-vector products that are necessary in your situation. I.e. ``expr2 = cvxpy.hstack([ D[i, :] @ Z[:, i] for i in range(img_len)])`` and then reassign ``expr2 = cvxpy.sum(expr2)``. The whole objective would then be ``cvxpy.Minimize(expr1 + expr2)``. Make sure to concatenate your original constraint list with the ``cons`` I've defined above.

Now for longer term solutions for @SteveDiamond to consider. If my guess is correct, the issue is just with allocating such a large amount of memory at once. We will probably need to add some input-checking or error handling that allows for more incremental memory allocation. For atoms like matmul this shouldn't be too hard to implement. However a general-purpose fix for this kind of issue might be too complicated. It might be best to just have a more informative error message, that directs a user to a special part of cvxpy documentation which addresses problems such as this. We could include this issue as one worked example.

@Aakriti05 please let us know if my proposed solution (allocating memory incrementally) works for you. I know it feels awkward, but the whole "introducing additional equality constraints" paradigm is actually employed by most solvers anyway, when canonicalizing the pnorm atom.

**Comment by akshayka** [comment] 2019-06-06 16:47
Re: a longer-term solution, std::vector stores its data in a contiguous block of memory. Using a different data structure, like std::deque, might help.

**Comment by Aakriti05** [comment] 2019-06-09 18:27
I tried on a system with 94 G of RAM and 32G of swap memory with the following code as suggested by @rileyjmurray and I got the memory error as attached below. Could you give some other suggestions to solve the memory error?

	```
Z = cp.Variable(shape=(img_len,img_len))
W = cp.Variable(shape=(img_len,img_len))
expr1 = cp.pnorm(W,2)
expr2 = cp.hstack([ D[i, :] @ Z[:, i] for i in range(img_len)])
expr2 = cp.sum(expr2)

objective = cp.Minimize(expr1 + expr2)	
cons = [Z >= 0, cp.sum(Z, axis=0) == 1]
constraints = [W[:, i] == C @ Z[:, i] for i in range(img_len)]
constraints += cons
print("Starting Optimization")
prob = cp.Problem(objective, constraints)
print("going to solve")
result = prob.solve("SCS", gpu=True, verbose=True)
```
Error - 
```
    result = prob.solve("SCS", gpu=False, verbose=True)
  File "/home/aakriti/anaconda3/envs/mycaffe/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 247, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/aakriti/anaconda3/envs/mycaffe/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 359, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "/home/aakriti/anaconda3/envs/mycaffe/lib/python3.5/site-packages/cvxpy/reductions/chain.py", line 58, in apply
    problem, inv = r.apply(problem)
  File "/home/aakriti/anaconda3/envs/mycaffe/lib/python3.5/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 218, in apply
    problem, zero_constr + neq_constr, self.EXP_CONE_ORDER)
  File "/home/aakriti/anaconda3/envs/mycaffe/lib/python3.5/site-packages/cvxpy/reductions/solvers/conic_solvers/conic_solver.py", line 264, in group_coeff_offset
    coeff = sp.vstack(matrices).tocsc()
  File "/home/aakriti/.local/lib/python3.5/site-packages/scipy/sparse/construct.py", line 499, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/home/aakriti/.local/lib/python3.5/site-packages/scipy/sparse/construct.py", line 555, in bmat
    A = _compressed_sparse_stack(blocks[:,0], 0)
  File "/home/aakriti/.local/lib/python3.5/site-packages/scipy/sparse/construct.py", line 407, in _compressed_sparse_stack
    data = np.concatenate([b.data for b in blocks])
MemoryError
```

**Comment by rileyjmurray** [comment] 2019-06-09 18:34
Okay at that point the error is happening in very standard numpy / scipy code. I'm not sure how much we can help resolve this. I am curious as to why the error happens with so much memory, however. Please check your memory utilization leading up to this error. Does it clearly increase until it fills up swap, or does the error show up when it seems like memory should be available? If you're in the second situation, the issue might be related to contiguous-memory limitations on your machine.

**Comment by Aakriti05** [comment] 2019-06-09 20:57
I am able to observe the RAM filling up, after which the SWAP memory fills up as well and once both are filled up, the MemoryError is thrown.

**Comment by rileyjmurray** [comment] 2019-06-09 23:09
If that's the case, I don't think there's much cvxpy  can do for you, at least for now. As Steven mentioned, essentially all existing solvers are going to require introducing a large number of constraints, and replicating the matrix ``C`` a total of ``img_len`` times just to represent the problem statement.

The only way you can move forward (short of finding a computer with more RAM) is to find a first-order solver which supports simple constraints (linear equations and inequalities) and accepts user-defined implementations to compute the objective value, and the gradient of the objective function. There might be something like this in ``scipy.optimize``, but I can't say for sure.

@SteveDiamond @akshayka I think we now have a good handle on this issue, but I am not sure if it is appropriate to close it. From what @Aakriti05 described after my proposed change of variables, I no longer think that contiguous memory is actually the problem here (I could well be wrong, since I've never worked in C++).

**Comment by SteveDiamond** [comment] 2019-06-10 23:41
I think it's fine to close this. The fundamental issue is that the problem matrix is too large. We haven't exposed any bugs in cvxpy with this, just a current limitation.

**Closed by SteveDiamond** 2019-06-10 23:41 UTC
Labels: bug
