### ISSUE TITLE
For small problems, CVXPY 1.0 is slower than 0.4.11

### ISSUE THREAD

**Issue by farrellm** [cvxgrp/cvxpy#409] opened 2017-11-14 21:03 UTC
For an equivalent problem, cvxpy 1.0 is take 3x of cvxpy 0.4.11 to compile and solve.

0.4.11

```python
def problem():
    x = cvx.Variable(8)
    mu = cvx.Parameter(8)

    u = mu.T * x - cvx.sum_squares(x) - 0.1 * cvx.sum_entries(cvx.abs(x) ** (3/2))
    c = [-0.2 <= x, x <= 0.2]

    return {"problem": cvx.Problem(cvx.Maximize(u), c),
            "variable": x,
            "forecast": mu}
```

1.0

```python
def problem():
    x = cvx.Variable(shape=(8,))
    mu = cvx.Parameter(shape=(8,))

    u = mu.T * x - cvx.sum_squares(x) - 0.1 * cvx.sum(cvx.abs(x) ** (3/2))
    c = [-0.2 <= x, x <= 0.2]

    return {"problem": cvx.Problem(cvx.Maximize(u), c),
            "variable": x,
            "forecast": mu}
```

common

```python
import time
import random
import statistics

import cvxpy as cvx
import numpy as np

def with_compile():
    p = problem()
    p["forecast"].value = np.random.normal(size=8)
    p["problem"].solve()
    return p


p0 = problem()
def without_compile():
    p0["forecast"].value = np.random.normal(size=8)
    p0["problem"].solve()
    return p0


functions = with_compile, without_compile
times = {f.__name__: [] for f in functions}

for i in range(100):  # adjust accordingly so whole thing takes a few sec
    func = random.choice(functions)
    t0 = time.time()
    func()
    t1 = time.time()
    times[func.__name__].append((t1 - t0) * 1000)

for name, numbers in times.items():
    print('FUNCTION:', name, 'Used', len(numbers), 'times')
    print('\tMEDIAN', statistics.median(numbers))
    print('\tMEAN  ', statistics.mean(numbers))
    print('\tSTDEV ', statistics.stdev(numbers))
```

**Comment by SteveDiamond** [comment] 2017-11-15 18:21
Thanks so much for trying out cvxpy 1.0! This is exactly the kind of feedback I was hoping for. I will look into this and try and speed things up.

**Comment by rileyjmurray** [comment] 2018-02-22 23:00
Following up on this. After running some pretty thorough tests on problems of various sizes, I've found that 
* cvxpy 1.0 and cvxpy 0.4 parse problems at the same asymptotic time complexity (i.e. if the compile time for 1.0 scales quadratically with some problem parameter, then the compile time for 0.4 will also scale quadratically with that parameter).
* cvxpy 1.0 is far more sensitive to vectorization than cvxpy 0.4. For example, I found that while vectorizing my models with 0.4 I would see a speedup of almost an order of magnitude, but vectorizing the same models in 1.0 saw a speedup of 2 to 3 orders of magnitude. There's even a new Jupyter notebook in the latest version of cvxpy 1.0 that demonstrates the importance of vectorization in compile time.

A factor of three slowdown for your example is pretty significant. However, one of the issues might be that on small problems, the overhead of cvxpy 1.0's backend is not amortized well. Could you try again with much larger problems, i.e. 100 or 1000 variables? In my experience I actually found that very large vectorized models with cvxpy 1.0 compiled faster than very large vectorized models with cvxpy 0.4.

**Comment by pietrodn** [comment] 2018-03-31 16:28
Can you try whether [this](https://github.com/cvxgrp/cvxpy/pull/458) helps?

**Comment by farrellm** [comment] 2018-04-05 22:00
I pulled the latest (through commit 973fa19) and generated a fresh conda environment. Unfortunately, the problem seems to have gotten worse, with 1.0 now 5x slower on the size 8 problem (median of 40 vs 8). Upping the dimensionality to 800, 1.0 does seem to scale a bit better (median of 400 vs 118).

This may be a red herring, but did anything change in the C side? If I recall correctly, I originally pulled and installed cvxpy without regenerating conda or running "make clean", and I saw the old 3x speed difference (medain 20 vs 8). But again, this could have been caused by any number of things. The current difference is repeatable.

**Comment by SteveDiamond** [comment] 2018-04-06 19:31
Hmm this will require more analysis. In my mind the scaling behavior is more important than the performance on small problems but we can look at both.

**Comment by pnystrup** [comment] 2018-06-12 06:15
@SteveDiamond remember the MPC portfolio application we worked on two years ago. I have an implementation of that, where I run a backtest. First I build the cvxpy problem, then I run a for loop where every step I do a couple of matrix multiplications to get the forecasts, which are then assigned to cvxpy parameters, then I solve the problem using ECOS, and store the result in np.arrays. Before upgrading cvxpy it took about four minutes to run the backtest 20 years back in time; after upgrading to cvxpy 1.0 it takes closer to 60 minutes! The actual solve times seem to be roughly the same. Is there anything in cvxpy 1.0 that could cause such a crazy increase in Python overhead (on Windows)?

**Comment by rileyjmurray** [comment] 2018-11-22 02:45
I have recently started using cvxpy for a new class of models, and while profiling code I found the following bottleneck. A particular "apply(...)" call results in several hundred if not thousands of calls to cvxcore.

![screenshot from 2018-11-21 17-31-03](https://user-images.githubusercontent.com/10662932/48877076-5faffd00-edb6-11e8-958b-bdb532c19805.png)

There are several calls to apply(...) whenever you invoke cvxpy, and the above image shows two separate types of "apply" calls. The following image shows the code for the apply(...) call in the yellow box (the one with 70635ms of runtime, and the one that turns 19 function calls into ~15,000 function calls). 

![likely compile-time bottleneck](https://user-images.githubusercontent.com/10662932/48877017-27a8ba00-edb6-11e8-97c7-cab34e0414d7.png)

The issue is that for problems with a large number of constraints (even a large number of sparse constraints), the double-for-loop over constraints (``con in problem.constraints``) and arguments (``arg in con.args``) is taking way too long. Looping over each ``con in constraints`` seems inevitable, but I wonder if the second loop could be accelerated. At the very least, we should develop an understanding of how different modeling tips (constraint vectorization, variable vectorization, and using cvxpy functions like ``cvxpy.sum`` instead of the corresponding built-in functions) affect the speed of each of these two loops.

**Comment by akshayka** [comment] 2018-12-05 22:09
Thanks for looking into this, @rileyjmurray! @SteveDiamond and I spoke about this, and one thing that will  certainly help is moving the double-for into C.  Another fruitful approach might be to parallelize the outer loop in Python.

**Comment by akshayka** [comment] 2019-01-17 19:42
Formatting SOC constraints is another bottleneck; specifically, the following Python for loop can dominate the parse time when a problem has a large SOC:

https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/conic_solver.py#L222-L231

Can we vectorize this loop?

**Comment by akshayka** [comment] 2019-01-18 20:36
@pnystrup Parameters don't actually short-circuit reparsing in 1.0, which might be why you're seeing the slow-down in your back-testing. @SteveDiamond and I are vectorizing various code paths in canonicalization, which should also help.

**Comment by SteveDiamond** [comment] 2019-01-19 00:44
I reduced the many calls to CVXcanon (now cvxcore) in MatrixStuffing to a single call. Not sure how much that speeded things up.

**Comment by akshayka** [comment] 2019-01-19 18:10
@farrellm , I re-ran your benchmark at master. The master branch is still slower than 0.4.11 for small problems, but it scales roughly the same as 0.4.11. Surprisingly, for the larger problems, parameters do not confer a speed-up in 0.4.11. 

I ran your benchmark for problem dimensions 8, 800, and 8000. Here are the median times in ms for constructing a problem and then solving it (`with_compile`).

|        | 8 | 800 | 8000 
|--------|---|-----|------|
| 0.4.11 | 10.9 | 304.7   | 3139.3    | 
| master | 28.7 | 292.7  | 3021.7   | 


And here are the median times for updating a problem via a parameter and then solving it (`without_compile`).

|        | 8 | 800 | 8000 
|--------|---|-----|------|
| 0.4.11 | 3.7| 287.3  | 3064.2    | 
| master | 27.2 | 297.7 | 3018.3   | 

I'll update the name of the issue to reflect theses findings.

**Closed** 2019-12-30 23:10 UTC
Labels: performance
