### ISSUE TITLE
[Windows] Overflow in canonicalization when reshaping sparse matrix

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#934] opened 2020-02-07 22:20 UTC
**Describe the bug**
During canonicalization of a problem with large data, the following error is encountered in Windows (but not MacOS or Linux):

```
ValueError: cannot reshape array of size -1390450388 into shape (1004, 'newshape')
```

This bug is present in the latest pre-release version of CVXPY, using SciPy 1.4.1.

This issue was originally reported on the cvxpylayers repository, https://github.com/cvxgrp/cvxpylayers/issues/45, by Github user urolyi1.

**To Reproduce**
Reproduce using

https://gist.github.com/urolyi1/fe94153f7a872046f1f73274391f6c51

In the linked-to script, replace the construction of the CvxpyLayer with a call to problem.solve(), after populating the parameters.

**Output**
File "C:\Users\Uro\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 271, in format_constraints
    reshaped_A = problem.A.reshape(restruct_mat.shape[1], -1, order='F').tocsr()

**Version**
 - OS: Windows
 - CVXPY Version: 1.1.0a2

**Additional context**
We've encountered issues similar to this one before, on Windows. Care should be taken to ensure that the fix doesn't cause a large slowdown in canonicalization, which has happened when fixing similar issues in the past.

**Comment by tm4droid** [comment] 2020-05-25 02:16
Is this issue's fix going to be part of the stable release? I can still see the problem in 1.1.0a4 on windows.
The issue only happens when the problem is DPP so my work around so far is to make the problem non DPP.

**Comment by tm4droid** [comment] 2020-05-27 07:24
A bit more information on this. It seems when a problem is deemed DPP, the parameter matrices are hugely inflated. For two equivalent problems non DPP SOCP problem has A matrix shape (410871, 1) while DPP version (410871, 51531), this creates overflow issues when creating and reshaping sparse matrices in Scipy.

**Comment by akshayka** [comment] 2020-05-28 16:13
We'll try to get a fix in soon, but the developers don't have too much bandwidth right now. Contributions would be welcome. 

Some additional context:
In an earlier version of Scipy, reshaping a large sparse matrix on any platform led to an overflow. They [implemented a fix](https://github.com/scipy/scipy/pull/9132), but it appears the issue remains on Windows (I can't replicate the overflow on Ubuntu, eg). Perhaps an issue should be opened in Scipy's repository.

The matrix A is inflated when the problem DPP because it represents an affine map from the parameters to the problem data. The actual problem data that's eventually passed to the solver should be of the same size as the non-DPP problem.

**Comment by SteveDiamond** [comment] 2020-05-29 00:52
Chiming in here, @tm4droid can you replicate the issue on Windows just by reshaping a sparse matrix? Then create an issue with that snippet in the SciPy repo. And you're sure you have the latest scipy?

**Comment by tm4droid** [comment] 2020-05-29 01:55
The issue can indeed be replicated just with SciPy. And I will raise an issue on its repo. But I'm betting there's a better chance Cvxpy finds a work around (maybe even by manually rearranging the block matrices), than SciPy fixing that in a timely manner.
This is may be the time as well for me to stress on the major speed up DPP mapping had on most of my problems. two orders of magnitude..

**Comment by tm4droid** [comment] 2020-05-29 02:44
@SteveDiamond  @akshayka , I played around with Scipy purely to reproduce the issue, and it turns out the overflow happens during simple dimension arithmetic calculation....
Which means if instead of passing a A.reshape((new_rows, -1)), you calculate column numbers on your own and call A.reshape((new_rows, new_cols)), there is no over flow.

so in conic_solver.py line 271, I propose a simple work around as:

unspecified, remainder = divmod(problem.A.shape[0] * problem.A.shape[1], restruct_mat.shape[1])
reshaped_A = problem.A.reshape(restruct_mat.shape[1], unspecified, order='F').tocsr()

**Comment by SteveDiamond** [comment] 2020-05-29 16:02
@tm4droid I committed the proposed fix. Try it again after installing from master?

**Comment by tm4droid** [comment] 2020-05-30 03:06
Tried it and it works in my case. Thanks a lot @SteveDiamond @akshayka

**Closed** 2020-05-30 18:47 UTC
