### ISSUE TITLE
Multiple calls of CVXPY solver throws “SolverError: Solver 'ECOS' failed”

### ISSUE THREAD

**Issue by malik201049** [cvxgrp/cvxpy#1204] opened 2021-01-05 19:44 UTC
I have some python function that solves an optimization problem in python using CVXPY and ECOS/MOSEK solvers. When I call the function repeatedly (within for loop) and pass different input variables at each iteration, I get "SolverError: Solver 'ECOS' failed". However, when I execute the same function with the same input variables outside the for loop, it works fine. I.e., when looping over the function I get SolverError, but when not looping, the results are fine. Could anyone please give the reason for such an issue?

**Comment by rileyjmurray** [comment] 2021-01-05 20:12
ECOS is less robust than MOSEK to numerical scaling issues. It's probably the case that your inputs are becoming "harder and harder" for ECOS as your loop runs. You should examine the time ECOS spends at solving each problem (does this increase as the loop runs?) and solution quality (do later solutions violate constraints by larger amounts?). If your problem has exponential or logarithmic terms there isn't a whole lot you can do to improve robustness of ECOS. If it's better to get *some* solution rather than no solution, then you can use SCS inside the loop. Just keep in mind that SCS sometimes returns solutions that violate constraints by pretty large margins, so you may need to increase the iteration limit and/or make the termination criteria smaller.

That said, if you are using ECOS at all when you have MOSEK, then my guess is that you have an instance-limited commercial license of MOSEK. If that's the case then the MOSEK support is a better bunch to ask for help. If your MOSEK license isn't instance-limited, then you should just use MOSEK in the loop instead of ECOS.

**Comment by malik201049** [comment] 2021-01-07 06:46
Thank you so much @rileyjmurray for your informative reply, its really helpful and I highly appreciate it. 
Indeed my problem contains logarithmic terms, and it is not complex to be solved anyway. However, the inputs are not becoming "harder and harder" they are "statistically" similar. I am, however, still confused why ECOS can solve the "same problem" for the "same input variables and settings" when called outside the loop, but it fails to solve it inside a loop. This, in my humble opinion, makes it fragile. I would really appreciate your help with this.  Thanks in advance

**Comment by rileyjmurray** [comment] 2021-01-07 13:03
>  I am, however, still confused why ECOS can solve the "same problem" for the "same input variables and settings" when called outside the loop, but it fails to solve it inside a loop.

Surely the problems are somehow different. Can you post some code here so we can reproduce the issue?

> One more thing, under the same settings, ECOS is performing better than MOSEK (mine with instance-limited commercial license), which most of the time produces the SolverError message.

That's very strange. I've never seen a problem family where ECOS is more reliable than MOSEK. Pinging @aszekMosek.

**Comment by malik201049** [comment] 2021-01-07 15:33
Thanks a lot for your reply @rileyjmurray. Please find my function below. I am also providing an instance of the input variables that 1) breaks my loop with "SolverError: Solver 'ECOS' failed" message and 2) where the MOSEK fails with "SolverError: Solver 'MOSEK' failed". Please note that when you execute the function with the ECOS solver directly (exactly as shown below), it solves the problem normally, but it, surprisingly, breaking my loop within the code.

``` <    
import numpy as np
import cvxpy as cvx
import cvxopt

def optimal_theoritical_solution(U, glu, Ru_min, PSD, Pl_max, Wl_max):
    P=cvx.Variable(U)
    gain =cvx.Parameter(U)
    gain.value =np.array(glu)
    min_rate = cvx.Parameter(U)
    min_rate.value = np.array(Ru_min)
    R = cvx.kl_div(Wl_max, (Wl_max + cvx.multiply(gain, P)/ PSD)) - cvx.multiply(gain, P)/ PSD
    objective=cvx.Minimize(cvx.sum(R/np.log(2)))
    constraints=[P>=0.0,
                 cvx.sum(P)-Pl_max==0.0,
                 min_rate.value + (1/np.log(2))*(cvx.kl_div(Wl_max, (Wl_max + cvx.multiply(gain, P)/ PSD)) - cvx.multiply(gain, P)/ PSD) <= 0.0
                 ]
    prob=cvx.Problem(objective, constraints)
    # prob.solve(solver= 'ECOS', verbose=False, max_iters=100000)  #'ECOS', 'SCS', or 'OSQP'
    # prob.solve(solver= 'ECOS', verbose=False, max_iters=100000)  #'ECOS', 'SCS', or 'OSQP'
    # prob.solve(solver='SCS', qcp = True)
    # prob.solve(solver='CVXOPT')
    prob.solve(solver='MOSEK', verbose=False)#, mosek_params={"MSK_DPAR_INTPNT_CO_TOL_NEAR_REL":  10})
    
    if prob.status == "infeasible":
        Rlu_python_optimize = 0#-np.inf
    else:
        Rlu_python_optimize = Wl_max * np.log2( np.ones(U) + np.divide(gain.value * P.value, Wl_max * PSD)) #; print(Rlu_python_optimiz )
        
    return prob.status,-prob.value,Rlu_python_optimize,P.value, np.sum(Rlu_python_optimize)


if __name__ == '__main__':    
    status,utility,rates,powers,totalRate = optimal_theoritical_solution(3, np.array([3.8429e-05 ,6.3654e-06 ,0.0000e+00]), np.array([2000000., 5000000.    ,   0.]),2e-15,10.0, 20000000.0)
> ```

**Comment by aszekMosek** [comment] 2021-01-07 16:12
For me MOSEK more or less solves the problem, and ECOS fails but I am not surprised that often it may go either way. The A matrix has elements such as 1e+10 and the solution has almost prohibitively humongous objective values and norm.  That will not work stably without a serious rescaling.


MOSEK warning 62: The A matrix contains a large value of  **1.9e+10** in constraint '' (0) at variable '' (7).
MOSEK warning 62: The A matrix contains a large value of  **1.9e+10** in constraint '' (0) at variable '' (16).

...

Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: -4.3736108800**e+08**   nrm: **3e+09**    Viol.  con: 1e+01    var: 4e+00    cones: 0e+00  
  Dual.    obj: -4.3736110235**e+08**   nrm: **1e+11**    Viol.  con: 0e+00    var: 0e+00    cones: 0e+00

**Comment by rileyjmurray** [comment] 2021-01-07 17:16
Thanks, @aszekMosek.

@malik201049, I agree with @aszekMosek's conclusion above. You cannot expect predictable solver behavior when your problem is scaled in that way. I'm going to close this issue again, but I have created a new GitHub issue about warning CVXPY users who supply badly scaled problems (that way you'd get a scaling warning even with open-source solvers like ECOS).

Feel free to comment here again if you manage to fix your scaling issue. If nothing else, users can benefit from seeing how you might have fixed the problem.

**Closed by rileyjmurray** 2021-01-07 17:16 UTC

**Comment by malik201049** [comment] 2021-01-08 16:34
Thank you @rileyjmurray  and @aszekMosek for your kind reply. 
> For me MOSEK more or less solves the problem
As far as I can see, there is a consensus that MOSEK is better than ECOS. Could you please tell me why my MOSEK fails most of the time compared to the ECOS?
Also, I am trying with the scaling without getting any better results, could you please suggest any scaling tricks based on the type of variables and problem settings that you have seen earlier?

**Comment by rileyjmurray** [comment] 2021-01-08 17:01
@malik201049 yes that's generally the consensus, but there will inevitably be some problems where one solver out-performs another. Both MOSEK and ECOS have extremely efficient linear algebra, although MOSEK's is multi-threaded. MOSEK also has pre-solve and simple automatic problem scaling. The biggest mathematical difference between MOSEK and ECOS is that MOSEK uses a "Mehrotra corrector" (or rather, a generalization thereof) as part of its underlying algorithm. Refer to https://github.com/embotech/ecos/issues/177#issuecomment-753571910 for discussion on how ECOS's current mathematics compares to that of MOSEK's.

With all that said, you seem to be in a situation where MOSEK is somehow not being as reliable as ECOS. This is not to be expected, and I'm sure the MOSEK developers would be happy to explore this problem class provided it's "reasonable". The "reasonable" qualifier here is important because from the perspective of numerical solvers, reliably handling problems with such massive constants requires a huge amount of engineering effort. The fact that ECOS sometimes succeeds on these problems is quite unusual, and not to be taken for granted.

For your problem, the source of the bad scaling comes from the term ``PSD``. You should see how you can scale problem variables so that that constant can takes reasonable values: certainly no smaller than ``1e-8``. You can also easily improve the scaling of the objective
```
R = cvx.kl_div(Wl_max, (Wl_max + cvx.multiply(gain, P)/ PSD)) - cvx.multiply(gain, P)/ PSD
objective=cvx.Minimize(cvx.sum(R/np.log(2)))
```
by multiply ``R`` by ``PSD``, or perhaps ``PSD**0.5``.

**Comment by malik201049** [comment] 2021-01-11 05:17
Many thanks @rileyjmurray  and @aszekMosek for your kind cooperation. I highly appreciate it. 
Please note that when I run "exactly the same program" on Colab, I don't face the above problem (i.e., SolverError randomly breaks my loop and stops the whole program even though there exists an optimal solution). Maybe there is some bug either in my Anaconda settings or in my local cvxpy/solvers settings, I don't know. However, I don't think that the scaling is the reason behind "randomly quitting my code".
Yet, for my problem shown above, I can confirm that the ECOS seems to be better than MOSEK, and it can successfully solve the problem, both in my local machine and Colab, most of the time when I keep changing the input variables.
