### ISSUE TITLE
CPLEX Solver Inconsistent Argument Lengths

### ISSUE THREAD

**Issue by siqilu12345** [cvxgrp/cvxpy#1215] opened 2021-01-20 01:58 UTC
**Describe the bug**
I'm using CVXPY with CPLEX solver(community edition). I just follow the example on the documentation and an error occurred: "cplex.exceptions.errors.CplexError: inconsistent argument lengths: obj, lb, ub, types, names, columns".

**To Reproduce**
import cvxpy as cp
x = cp.Variable(2)
obj = cp.Minimize(x[0] + cp.norm(x, 1))
constraints = [x >= 2]
prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.CPLEX)

**Expected behavior**
If I change the solver option to other solvers, like SCS, the problem can be solved correctly.

**Output**
Traceback (most recent call last):
  File "C:/.../cvx_solve.py", line 460, in <module>
    cvx_solver()
  File "C:/.../cvx_solve.py", line 51, in cvx_solver
    prob.solve(solver=cp.CPLEX)
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\problems\problem.py", line 401, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\problems\problem.py", line 817, in _solve
    solution = solving_chain.solve_via_data(
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 323, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\reductions\solvers\qp_solvers\cplex_qpif.py", line 107, in solve_via_data
    var_idx = list(model.variables.add(obj=q,
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cplex\_internal\_subinterfaces.py", line 458, in add
    return self._add_iter(self.get_num, self._add,
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cplex\_internal\_baseinterface.py", line 41, in _add_iter
    addfun(*args, **kwargs)
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cplex\_internal\_subinterfaces.py", line 374, in _add
    validate_arg_lengths(
  File "C:\...\AppData\Local\Programs\Python\Python38\lib\site-packages\cplex\_internal\_aux_functions.py", line 99, in validate_arg_lengths
    raise CplexError("inconsistent argument lengths" + extra_msg)
cplex.exceptions.errors.CplexError: inconsistent argument lengths: obj, lb, ub, types, names, columns

**Version**
 - OS: Windows10 64bit 
 - CVXPY Version: 1.1.7
 - Python Version: 3.8

**Additional context**

**Comment by phschiele** [comment] 2021-02-06 00:44
I recently ran into the same error. It looks like adding the variable names in #1169 is causing the dimension mismatch. 
As mentioned in the PR, cvxpy can change the (number of) variables under the hood.
In this particular case, the reduction chain looks like:
```python
[<cvxpy.reductions.cvx_attr2constr.CvxAttr2Constr at 0x7f0dd17f4950>,
 <cvxpy.reductions.qp2quad_form.qp2symbolic_qp.Qp2SymbolicQp at 0x7f0dd17f4910>,
 <cvxpy.reductions.qp2quad_form.qp_matrix_stuffing.QpMatrixStuffing at 0x7f0dd17f4a50>,
 <cvxpy.reductions.solvers.qp_solvers.cplex_qpif.CPLEX at 0x7f0dd6103f90>]
```
During the canonicalization in `Qp2SymbolicQp`, the length of the variable changes from two to four, causing the mismatch when calling the solver.

Broadly speaking, there are three possible solutions I could think of:
- always adapting the variable names when changing the length of the variables (unnecessary for most use cases?)
- only passing the names if the length matches ("quick and dirty")
- removing the variable names again (obviously, adding the names was an improvement, as explained in the PR)

**Comment by SteveDiamond** [comment] 2021-02-06 03:23
I'm sorry, I don't really understand the bug. Are variable names supposed to be scalars? Why would it matter how many there are?

**Comment by phschiele** [comment] 2021-02-06 09:56
When running the example posted in the issue, an exception is raised during this part of `cplex_qpif`'s `solve_via_data()` call:
```python
var_idx = list(model.variables.add(obj=q,
                                   lb=-cpx.infinity*np.ones(n_var),
                                   ub=cpx.infinity*np.ones(n_var),
                                   names=variable_names))
```
Here, all inputs must have the same length. Since in the original specification, the decision variable is of length two (`x = cp.Variable(2)`), `variable_names` has length two. However, the problem is being transformed by cvxpy to now have four scalar variables (`q` and `n_var` are of length four.

I have just checked out the branch of #1170 locally, and it already solves this bug here as well.

**Comment by SteveDiamond** [comment] 2021-02-06 21:33
You're welcome to use #1170 locally but I'm not comfortable merging it into master. If cplex is crashing due to #1169 I vote to revert it. @akshayka @rileyjmurray what do you think?

**Comment by rileyjmurray** [comment] 2021-02-07 00:09
@SteveDiamond I'd favor creating a new ``qp_var_names`` branch of cvxgrp/cvxpy based on the current master state, merge #1170 into ``qp_var_names``, and then revert #1169 on master. My reasoning is that I think the collective changes in these two PRs seem to get us most of the way to basic variable-name propagation for all QP solvers (I mean, they only fully implement it for CPLEX, but #1170 looks like it's setting up all QP solvers to take advantage of this). That's a really valuable feature so I'd like to set things up in a way where the current work isn't lost. There's a chance I'd be open to merging the hypothetical ``qp_var_names`` into master with a small set of changes, but I can't say for sure right now.

**Comment by SteveDiamond** [comment] 2021-02-07 01:11
I followed @rileyjmurray 's suggestion and created the qp_var_names branch with #1170 merged in. I've reverted #1169 on master.

**Closed by SteveDiamond** 2021-02-07 01:11 UTC
