### ISSUE TITLE
Cplex and Gurobi python interfaces very slow

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#617] opened 2018-10-24 15:17 UTC
Gurobi calls seem much slower than Mosek or OSQP. For example, in this script solving multiple QPs

```python
import numpy as np
import scipy as sp
import scipy.sparse as sparse
from cvxpy import *
import time


def solve_problem(solver):
    start_time = time.time()
    x = Variable(n)
    gamma = Parameter(nonneg=True)
    objective = 0.5*sum_squares(A*x - b) + gamma*norm1(x)
    prob = Problem(Minimize(objective))

    # Solve problem for different values of gamma parameter
    avg_solve_time = 0
    for gamma_val in gammas:
        gamma.value = gamma_val
        prob.solve(solver=solver, warm_start=True)
        avg_solve_time += prob.solver_stats.solve_time/len(gammas)
    end_time = time.time()

    return end_time - start_time, avg_solve_time


if __name__ == "__main__":
    sp.random.seed(1)
    n = 100
    m = 1000
    A = sparse.random(m, n, density=0.5)
    x_true = np.multiply((np.random.rand(n) > 0.8).astype(float),
                         np.random.randn(n)) / np.sqrt(n)
    b = A.dot(x_true) + 0.5*np.random.randn(m)
    gammas = np.linspace(1, 10, 50)

    total_gurobi, solve_gurobi = solve_problem('GUROBI')
    total_mosek, solve_mosek = solve_problem('MOSEK')
    total_osqp, solve_osqp = solve_problem('OSQP')

    print("GUROBI: total: %.2e, solve: %.2e" % (total_gurobi, solve_gurobi))
    print("MOSEK: total: %.2e, solve: %.2e" % (total_mosek, solve_mosek))
    print("OSQP: total: %.2e, solve: %.2e" % (total_osqp, solve_osqp))
```

I get:
```
GUROBI: total: 1.48e+01, solve: 1.02e-01
MOSEK: total: 5.63e+00, solve: 5.29e-02
OSQP: total: 3.05e+00, solve: 5.66e-03
```

You can find the profiling results here 
[profiling.prof.zip](https://github.com/cvxgrp/cvxpy/files/2511099/profiling.prof.zip)

I looks like the function [solve_via_data](https://github.com/cvxgrp/cvxpy/blob/b53c13a79324993ec090743f9394bca115efc96b/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py#L93) is very slow.

@gglockner would you have any suggestion on how to speed up the Gurobi python call?

**Comment by gglockner** [comment] 2018-10-24 16:21
@bstellato I might be able to help - can you help by profiling the solve_via_data function?

**Comment by bstellato** [comment] 2018-10-24 18:41
If you run the following commands on the profiling attachment above

```python
import pstats
from pstats import SortKey
p = pstats.Stats("./profiling.prof")
p.strip_dirs().sort_stats(SortKey.CUMULATIVE).print_stats('gurobi_qpif')

```

you get

```
         2729423 function calls (2567672 primitive calls) in 24.279 seconds

   Ordered by: cumulative time
   List reduced from 2493 to 11 due to restriction <'gurobi_qpif'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       50   10.700    0.214   11.356    0.227 gurobi_qpif.py:93(solve_via_data)
    50000    0.366    0.000    0.366    0.000 gurobi_qpif.py:132(<listcomp>)
       50    0.006    0.000    0.221    0.004 gurobi_qpif.py:52(invert)
       50    0.101    0.002    0.101    0.002 gurobi_qpif.py:78(<listcomp>)
       50    0.099    0.002    0.099    0.002 gurobi_qpif.py:68(<listcomp>)
      100    0.025    0.000    0.025    0.000 gurobi_qpif.py:9(constrain_gurobi_infty)
    10000    0.015    0.000    0.015    0.000 gurobi_qpif.py:144(<listcomp>)
        1    0.000    0.000    0.000    0.000 gurobi_qpif.py:1(<module>)
       51    0.000    0.000    0.000    0.000 gurobi_qpif.py:45(name)
        1    0.000    0.000    0.000    0.000 gurobi_qpif.py:24(GUROBI)
        1    0.000    0.000    0.000    0.000 gurobi_qpif.py:48(import_solver)
```

I haven't done a line by line profiling yet.

**Comment by bstellato** [comment] 2018-10-24 18:59
Result from `line_profiler`:

```
Timer unit: 1e-06 s

Total time: 14.6353 s
File: /Users/sidereus/Dropbox/research/code/projects/cvxpy/build/lib.macosx-10.13-x86_64-3.7/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py
Function: solve_via_data at line 93

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    93                                               @profile
    94                                               def solve_via_data(self, data, warm_start, verbose, solver_opts, solver_cache=None):
    95        50        252.0      5.0      0.0          import gurobipy as grb
    96                                                   # N.B. Here we assume that the matrices in data are in csc format
    97        50       9220.0    184.4      0.1          P = data[s.P].tocoo()       # Convert matrix to coo format
    98        50        133.0      2.7      0.0          q = data[s.Q]
    99        50      39931.0    798.6      0.3          A = data[s.A].tocsr()       # Convert A matrix to csr format
   100        50        143.0      2.9      0.0          b = data[s.B]
   101        50       9248.0    185.0      0.1          F = data[s.F].tocsr()       # Convert F matrix to csr format
   102        50        131.0      2.6      0.0          g = data[s.G]
   103        50         73.0      1.5      0.0          n = data['n_var']
   104
   105                                                   # Constrain values between bounds
   106        50      50455.0   1009.1      0.3          constrain_gurobi_infty(b)
   107        50      10006.0    200.1      0.1          constrain_gurobi_infty(g)
   108
   109                                                   # Create a new model
   110        50       8530.0    170.6      0.1          model = grb.Model()
   111
   112                                                   # Add variables
   113     60050      93750.0      1.6      0.6          for i in range(n):
   114                                                       # Set variable type.
   115     60000     104077.0      1.7      0.7              if i in data[s.BOOL_IDX]:
   116                                                           vtype = grb.GRB.BINARY
   117     60000      98538.0      1.6      0.7              elif i in data[s.INT_IDX]:
   118                                                           vtype = grb.GRB.INTEGER
   119                                                       else:
   120     60000      95157.0      1.6      0.7                  vtype = grb.GRB.CONTINUOUS
   121     60000     101982.0      1.7      0.7              model.addVar(ub=grb.GRB.INFINITY,
   122     60000      95838.0      1.6      0.7                           lb=-grb.GRB.INFINITY,
   123     60000     370617.0      6.2      2.5                           vtype=vtype)
   124        50      22512.0    450.2      0.2          model.update()
   125        50        592.0     11.8      0.0          x = model.getVars()
   126
   127                                                   # Add equality constraints: iterate over the rows of A
   128                                                   # adding each row into the model
   129        50        336.0      6.7      0.0          if A.shape[0] > 0:
   130     50050      93189.0      1.9      0.6              for i in range(A.shape[0]):
   131     50000     111278.0      2.2      0.8                  start = A.indptr[i]
   132     50000      96148.0      1.9      0.7                  end = A.indptr[i+1]
   133     50000     963048.0     19.3      6.6                  variables = [x[j] for j in A.indices[start:end]]  # Get nnz
   134     50000     115520.0      2.3      0.8                  coeff = A.data[start:end]
   135     50000    1001337.0     20.0      6.8                  expr = grb.LinExpr(coeff, variables)
   136     50000    2285947.0     45.7     15.6                  model.addConstr(expr, grb.GRB.EQUAL, b[i])
   137        50      52352.0   1047.0      0.4          model.update()
   138
   139                                                   # Add inequality constraints: iterate over the rows of F
   140                                                   # adding each row into the model
   141        50        451.0      9.0      0.0          if F.shape[0] > 0:
   142     10050      17961.0      1.8      0.1              for i in range(F.shape[0]):
   143     10000      20651.0      2.1      0.1                  start = F.indptr[i]
   144     10000      18878.0      1.9      0.1                  end = F.indptr[i+1]
   145     10000      59051.0      5.9      0.4                  variables = [x[j] for j in F.indices[start:end]]  # Get nnz
   146     10000      21440.0      2.1      0.1                  coeff = F.data[start:end]
   147     10000      46814.0      4.7      0.3                  expr = grb.LinExpr(coeff, variables)
   148     10000     172454.0     17.2      1.2                  model.addConstr(expr, grb.GRB.LESS_EQUAL, g[i])
   149        50      15488.0    309.8      0.1          model.update()
   150
   151                                                   # Define objective
   152        50        613.0     12.3      0.0          obj = grb.QuadExpr()
   153        50       8186.0    163.7      0.1          if P.count_nonzero():  # If there are any nonzero elms in P
   154     50050      95036.0      1.9      0.6              for i in range(P.nnz):
   155     50000    2521473.0     50.4     17.2                  obj.add(.5*P.data[i]*x[P.row[i]]*x[P.col[i]])
   156        50      21666.0    433.3      0.1          obj.add(grb.LinExpr(q, x))  # Add linear part
   157        50     166385.0   3327.7      1.1          model.setObjective(obj)  # Set objective
   158        50       2262.0     45.2      0.0          model.update()
   159
   160                                                   # Set verbosity and other parameters
   161        50       1778.0     35.6      0.0          model.setParam("OutputFlag", verbose)
   162                                                   # TODO user option to not compute duals.
   163        50        617.0     12.3      0.0          model.setParam("QCPDual", True)
   164
   165        50        359.0      7.2      0.0          for key, value in list(solver_opts.items()):
   166                                                       model.setParam(key, value)
   167
   168                                                   # Update model
   169        50        550.0     11.0      0.0          model.update()
   170
   171                                                   # Solve problem
   172        50         98.0      2.0      0.0          results_dict = {}
   173        50         83.0      1.7      0.0          try:
   174                                                       # Solve
   175        50    5612203.0 112244.1     38.3              model.optimize()
   176                                                   except Exception:  # Error in the solution
   177                                                       results_dict["status"] = s.SOLVER_ERROR
   178
   179        50        320.0      6.4      0.0          results_dict["model"] = model
   180
   181        50        107.0      2.1      0.0          return results_dict
```

Note that the times are scaled by `Timer unit` at the top.

**Comment by bstellato** [comment] 2018-10-28 15:29
By the way, the CPLEX calls are even slower than GUROBI: @rkersh 

```
CPLEX: total: 3.90e+01, solve: 6.50e-01
```

**Comment by bstellato** [comment] 2019-02-12 18:43
@gglockner @rkersh Do you have any plans to solve this? Having a sparse matrix input like Matlab would fix it. Most of the time is spent in the low level interface functions. The actual cvxpy canonicalization turns out to be much cheaper.

**Comment by rkersh** [comment] 2019-02-12 19:52
@bstellato: I took a quick look when solving with CPLEX. While this doesn't address the issue of having a Matlab style matrix input, you can improve things by adding linear constraints in batches rather than one at a time in cplex_qpif.py (as is done in cplex_intf.py). For example:
```
diff --git a/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py b/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
index a51452d..bb49a7d 100644
--- a/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
+++ b/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py
@@ -123,23 +123,29 @@ class CPLEX(QpSolver):
                                       model.variables.type.integer)
 
         # Add constraints
+        lin_expr, rhs = [], []
         for i in range(n_eq):  # Add equalities
             start = A.indptr[i]
             end = A.indptr[i+1]
-            row = [[A.indices[start:end].tolist(),
-                   A.data[start:end].tolist()]]
-            model.linear_constraints.add(lin_expr=row,
-                                         senses=["E"],
-                                         rhs=[b[i]])
-
+            lin_expr.append([A.indices[start:end].tolist(),
+                             A.data[start:end].tolist()])
+            rhs.append(b[i])
+        if lin_expr:
+            model.linear_constraints.add(lin_expr=lin_expr,
+                                         senses=["E"] * len(lin_expr),
+                                         rhs=rhs)
+
+        lin_expr, rhs = [], []
         for i in range(n_ineq):  # Add inequalities
             start = F.indptr[i]
             end = F.indptr[i+1]
-            row = [[F.indices[start:end].tolist(),
-                   F.data[start:end].tolist()]]
-            model.linear_constraints.add(lin_expr=row,
-                                         senses=["L"],
-                                         rhs=[g[i]])
+            lin_expr.append([F.indices[start:end].tolist(),
+                             F.data[start:end].tolist()])
+            rhs.append(g[i])
+        if lin_expr:
+            model.linear_constraints.add(lin_expr=lin_expr,
+                                         senses=["L"] * len(lin_expr),
+                                         rhs=rhs)
 
         # Set quadratic Cost
         if P.count_nonzero():  # Only if quadratic form is not null
```

**Comment by rluce** [comment] 2019-02-13 14:31
@bstellato I looked at what happens in `gurobi_qpif.py`, and I see two different problems.  The first is the bottleneck caused by `gurobipy` not accepting `scipy.sparse` matrices, as you noted already above.  I need to think about this a little more.

The second performance problem is the term-by-term assembly of the `QuadExpr` object. Consider the following box-constrained QP:
```
import numpy as np
import scipy as sp
import scipy.sparse as sparse
from cvxpy import *
import time

def solve_quadminbox(n, density):
    Q = sparse.random(n, n, density=density)
    Q = Q.T.dot(Q)
    p = np.random.rand(n)
    start_time = time.time()
    x = Variable(n)
    obj = quad_form(x, Q) + p.T * x
    prob = Problem(Minimize(obj), [x >= -1.0, x <= 1.0])
    prob.solve(solver='GUROBI', verbose=False)
    total_time = time.time() - start_time
    solve_time = prob.solver_stats.solve_time
    return (total_time, solve_time)

if __name__ == "__main__":
    sp.random.seed(1)
    fmt = ("total={0:5.2f}s solve={1:5.2f}s")
    (t_tot, t_sol) = solve_quadminbox(500, 0.25)
    print(fmt.format(t_tot, t_sol))
```

With current master I see on my box
```
total= 9.02s solve= 0.19s
```
but with a simple change in [my branch](https://github.com/rluce/cvxpy/tree/passqtriplets) this becomes
```
total= 0.66s solve= 0.19s
```

For the original benchmark script above, the efffect is on my box:
```
GUROBI: total: 1.03e+01, solve: 7.40e-02  # old
GUROBI: total: 8.90e+00, solve: 7.45e-02  # new
```
so it helps a little bit there, too.

Would you like to put this two-line change in, or should make a pull request?

**Comment by SteveDiamond** [comment] 2019-03-13 17:35
Since we've improved the CPLEX and Gurobi interfaces as much as we can given that they don't yet take sparse matrices, I'm going to close this issue.

**Closed by SteveDiamond** 2019-03-13 17:35 UTC
Labels: speed

**Comment by bstellato** [comment] 2019-03-13 18:12
For the record, Gurobi will support it from the next bugfix release and this is already included in CVXPY.

**Comment by carlosgmartin** [comment] 2019-12-05 23:35
@bstellato @SteveDiamond What's the current way to pass the numpy arrays corresponding to the parameters, as in [`cvxopt.solvers.lp`](https://cvxopt.org/userguide/coneprog.html#cvxopt.solvers.lp), to CPLEX directly? I need a blazing fast function and model specification is also turning out to be my major bottleneck.

**Comment by rkersh** [comment] 2019-12-05 23:43
@carlosgmartin: there is currently no equivalent to this for the CPLEX interface. You would probably get the best performance calling the [CPLEX Python API](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.9.0/ilog.odms.cplex.help/refpythoncplex/html/cplex.Cplex-class.html) directly, but then you wouldn't get the nice modeling language functionality and the solver independent framework provided by `cvxpy`. Another alternative would be to call [docplex](https://pypi.org/project/docplex/), which is a modeling language built on top of the CPLEX Python API.

**Comment by carlosgmartin** [comment] 2019-12-05 23:45
@rkersh What about Gurobi?

I think the CPLEX Python API has [the same problem](https://stackoverflow.com/questions/50714397/cplex-with-python-api-how-to-make-model-formulating-faster).

**Comment by rkersh** [comment] 2019-12-05 23:53
@carlosgmartin: You are correct with regards to the CPLEX Python API, but working at the lower level would still give you the best performance as you would have more control over the finer details.

Otherwise, I can't speak to the Gurobi interface. Maybe one of the other participants here can provide detail on that. The stackoverflow thread seems to say that it has the same issue, though.

**Comment by SteveDiamond** [comment] 2019-12-06 00:15
Gurobi has a direct sparse matrix interface now.

**Comment by carlosgmartin** [comment] 2019-12-06 00:36
@SteveDiamond Do you happen to know whether Gurobi has an analogue to the CXVOPT-like interface, where parameters can be passed directly (in raw array form) rather than constructed as symbolic-like expression trees (which is the source of slowness)? I'm looking through their [Python API documentation](https://www.gurobi.com/documentation/9.0/refman/py_model.html#pythonclass:Model) but am having trouble finding it (if there is one).

**Comment by SteveDiamond** [comment] 2019-12-06 00:46
@carlosgmartin Yes you can pass in SciPy sparse matrices and NumPy arrays. You can see the interface in use here: https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/gurobi_conif.py

**Comment by carlosgmartin** [comment] 2019-12-12 06:33
@SteveDiamond Unfortunately that still (from what I can see) uses Python loops. I did find the Gurobi Python API functions [`addMVar`](https://www.gurobi.com/documentation/9.0/refman/py_model_addmvar.html), [`addMConstrs`](https://www.gurobi.com/documentation/9.0/refman/py_model_addmconstrs.html) and [`setMObjective`](https://www.gurobi.com/documentation/9.0/refman/py_model_setmobjective.html), which directly take NumPy ndarrays and SciPy sparse matrices as input. Nonetheless, the model specification process is still slow (I've seen this issue raised online in multiple places), so it looks like a fundamental problem with their Python API. Someone made an unofficial alternative Python API that is supposed to be faster: https://github.com/supermihi/gurobimh.

**Comment by rluce** [comment] 2019-12-12 07:05
@carlosgmartin 

>  I did find the Gurobi Python API functions `addMVar`, `addMConstrs` and `setMObjective` [...] Nonetheless, the model specification process is still slow

Could you maybe post a specific example that points at a bottleneck on the gurobipy side?  I can take a look then.

Here is a little bit of background:  There are two layers of the "matrix friendly" API:  One layer of (rather simple) modeling objects (`MVar`, `MLinExpr`, etc.), and a lower level API that just accepts data from sparse matrices (or ndarrays) (e.g., `Model.addMConstrs()` and friends).  The latter is used from CVXPY in the [QP interface](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py) (the conic interface hasn't been polished up using this API yet).  The overhead for using this API should be very small.

**Comment by carlosgmartin** [comment] 2019-12-20 20:33
@rluce The overhead might come from the fact that, for the specific problem I'm working on, I need to repeatedly solve a very large number of relatively small LPs.

One way to do this (my original approach) is to iterate over these LPs—creating a model each time and solving it—and combine the solutions.

Another way I'm exploring is to pass the parameters of my LPs to a C program (using the Numpy C API), which then uses the Gurobi C API to solve them as quickly as possible and returns the solutions back to the Python script (again using the Numpy C API). 

I've also asked a question about this [on the Gurobi forums](https://support.gurobi.com/hc/en-us/community/posts/360055683232-Solving-LPs-sequentially-versus-one-large-LP-with-non-interacting-variables-constraints).
