### ISSUE TITLE
Dynamic Price -- TypeError: <class 'cvxpy.constraints.leq_constraint.LeqConstraint'> is not a valid type for a Constant value.

### ISSUE THREAD

**Issue by jackalack** [cvxgrp/cvxpy#404] opened 2017-10-26 21:25 UTC
My goal is to have a dynamic price based on the outcome of a decision variable.  Below I have create a toy example where the price of x is dependent on whether the solved for value is greater than or equal to 4.  

`from cvxpy import *`

`x = Variable()`
`y = Variable()`

`constraints = [x + y <= 10]`

`obj = Maximize(x * 5 * (x<4) + (x-4) * 10 * (x>=4) + y*7)`

`prob = Problem(obj, constraints)`
`prob.solve()`

When I try to run this code I get:

`TypeError: <class 'cvxpy.constraints.leq_constraint.LeqConstraint'> is not a valid type for a Constant value.`

Any ideas of how I can enable a dynamic cost?

**Comment by SteveDiamond** [comment] 2017-10-26 23:43
Yeah, you can't make boolean variables like that. Try ``z = Bool()`` and ``x <= 4 + C*z`` where ``C`` is large. That's the simplest answer but probably not the best.

**Comment by jackalack** [comment] 2017-10-30 00:50
thank you @SteveDiamond.  I just tried your recommendation, but received a DCP error.  In case I incorrectly applied your advice, here is the code I used:

<img width="557" alt="screen shot 2017-10-29 at 5 44 44 pm" src="https://user-images.githubusercontent.com/7672771/32150529-8c1ab0ae-bcd1-11e7-86b5-ee5da18a311f.png">

I have been experimenting with various formulations, and it appears that I receive a DCP error whenever I try to multiply a `cvx.Bool()` with a `cvx.Variable()`. For example:

<img width="579" alt="screen shot 2017-10-29 at 5 49 19 pm" src="https://user-images.githubusercontent.com/7672771/32150533-972f6c5a-bcd1-11e7-8e7a-7d4ae624f825.png">

What am I doing incorrectly?

**Comment by rileyjmurray** [comment] 2018-04-29 08:52
This is a pretty standard modeling problem for mixed-integer programming. Your objective needs the term `+5 * x * z`, and we need to express this without multiplying variables ("Bool()" being a type of variable). At a high level, the solution is to introduce a variable `xz`, and additional constraints that force `xz` to zero when `z = 0`, and otherwise allow `xz` to be as large as `x`.

The exact *way* you formulate these constraints depends on your problem. To be familiar with the general techniques, consider getting a book on integer programming modeling.

Marking as closed, since the issue is unrelated to cvxpy correctness or features.

**Closed by rileyjmurray** 2018-04-29 08:52 UTC
