### ISSUE TITLE
Anaconda installs version 0.4.9

### ISSUE THREAD

**Issue by gobbedy** [cvxgrp/cvxpy#499] opened 2018-05-25 11:16 UTC
Hello,

Thanks for this great library, and apologies if my question is stupid.

According to the cvxpy.org (http://www.cvxpy.org/versions/index.html), the latest stable release is version 1.0, and previous versions are not supported.

However, I strictly followed the installation steps (http://www.cvxpy.org/install/index.html) and anaconda installed cvxpy version 0.4.9 (cvxpy.\_\_version\_\_ is 0.4.9).

I installed the latest version of Anaconda (5.1.0) on Linux, if that helps.

Unless I screwed up somehow (very possible), it means the officially recommended installation steps result in an officially unsupported version of cvxpy.

Side note: I also notice that "multiply" is not documented: http://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html#multiply

**Comment by matthewgilbert** [comment] 2018-05-25 22:06
I am getting a similar issue. When I attempt `conda install -c cvxgrp cvxpy=1.0.1` I get
```
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - cvxpy 1.0.1* -> lapack

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/cvxgrp/linux-64
  - https://conda.anaconda.org/cvxgrp/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by matthewgilbert** [comment] 2018-05-26 17:11
This was resolved for me by borrowing from the `cvxpy/continuous_integration/install.sh` script

```
conda install -q -n test-environment -c conda-forge lapack
```

**Comment by gobbedy** [comment] 2018-05-26 21:48
Woah @matthewgilbert that worked for me too. Thanks!

So
conda install -c conda-forge lapack

should be added to the official install steps

**Comment by SteveDiamond** [comment] 2018-05-27 17:19
The install instructions have been updated.

**Comment by mfocchi** [comment] 2019-04-17 15:59
all this is very bad, the installation instructions of cvxpy should be update!!! they are not!

**Comment by ericwbzhang** [comment] 2019-04-17 23:29
Currently the CVXPY 1.0.2 version document is not updated. Installation by conda is still some ancient version....

**Comment by akshayka** [comment] 2019-04-17 23:43
@ericwbzhang , can you explain what you mean?

@SteveDiamond , @rileyjmurray , do you know anything about this issue? (I use pip+virtualenv instead of conda, so I never see any of these issues personally ...)

**Comment by SteveDiamond** [comment] 2019-04-18 01:31
@akshayka I don't know why they would get old anaconda versions. I updated the install instructions to require lapack and cvxpy=1.0.21 (version number will be updated by bumpversion). That should stop these old installs.

**Comment by mfocchi** [comment] 2019-04-18 08:09
is it possible to have the install instructions of the correct version without conda?

**Comment by ericwbzhang** [comment] 2019-04-18 13:29
I tried 
conda install -c cvxgrp cvxpy= 1.0.21 (or 1.0.1)

but it returns package not found. I have lapack installed.

**Comment by ericwbzhang** [comment] 2019-04-18 15:00
Update: 
I did some search and it seems to be a problem only for Anaconda user on Windows. 

https://github.com/cvxgrp/cvxpy/issues/701

**Comment by matthewgilbert** [comment] 2019-04-21 06:25
I am no expert on conda packaging, but it may be worthwhile putting `cvxpy` on the `conda-forge` channel instead of maintaining your own `cvxpy` channel on https://anaconda.org/.

In my experience getting all the continuous integration working for linux/mac/windows is quite painful. One of the advantages of using conda-forge is they have a pretty straightforward framework for getting builds across all three platforms and pretty solid support via their gitter channel. This would also simplify the user experience to just running `conda install -c conda-forge cvxpy`

**Comment by SteveDiamond** [comment] 2019-05-03 18:43
@matthewgilbert thanks for the suggestion. I'm considering simply removing the instructions for installation with Anaconda. We switched to suggesting installation with pip a few months ago. We'll still put out conda versions with each new release, but people can find them on their own perhaps.

**Comment by akshayka** [comment] 2019-05-03 19:33
Alternatively, if we can get conda forge working, we can just tell conda users to install cvxpy via conda forge instead of cvxgrp. But it looks like cvxpy on conda forge is several versions behind the current version. The pull requests for updates were never merged in, because they failed the CI tests: https://github.com/conda-forge/cvxpy-feedstock/pulls. I don't have the time right now to fix this, and Steven probably doesn't either.

If someone wants to look into this and help us get the conda-forge recipe working, that would be really great! I know conda is important for windows users in particular.

**Comment by rileyjmurray** [comment] 2019-06-20 18:34
Weirdly, I'm trying to install cvxpy on a new macbook pro, and I'm also getting this issue.

**Comment by rileyjmurray** [comment] 2020-02-26 06:21
The discussion on this thread is now a duplicate of #937 (planned conda-forge integration).

**Closed by rileyjmurray** 2020-02-26 06:21 UTC
Labels: installation
