### ISSUE TITLE
Update Travis environment PYPI_SERVER

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#738] opened 2019-05-31 21:11 UTC
CVXPY version 1.0.24 was recently uploaded to PyPi. This release includes a Windows wheel and egg. However, unlike previous releases, it does not include a source archive for installation on Mac OS X and Linux. See https://pypi.org/project/cvxpy/1.0.24/#files

Here's the latest Travis build: https://travis-ci.org/cvxgrp/cvxpy/builds/539866720

I'm not too familiar with deployment, so I'm not sure what the issue is. The 2.7 builds failed, but the MAC OS X and Linux builds with DEPLOY_PYPI="true" succeeded.

@rileyjmurray @SteveDiamond , any ideas what might be happening?

**Comment by rileyjmurray** [comment] 2019-05-31 22:21
I think the issue may be in how version_getter.py and upload logic behave for pypi. They were written under the assumption that the cvxpy distribution on pypi was a source distribution. Now that there are wheels for Windows, the script to handle source distribution uploads to pypi think that those wheels are actually source distributions.

I will fix this late this next week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rileyjmurray** [comment] 2019-05-31 22:42
Okay I can confirm that my previous comment is almost certainly right about the issue. The only “upload to pypi” builds used Python 3.6, and there is currently a Python 3.6 egg and Windows wheel sitting on pypi (as a result of Windows deployment improvements).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshayka** [comment] 2019-05-31 23:33
Thanks for triaging this! I'll assign this issue to you, then.

**Comment by akshayka** [comment] 2019-06-01 17:20
I took a shot at fixing this in 3cbe741f48a1c369e8597f91db5ce2fde578645e. I'll keep this issue open until I can verify that the fix works.

**Comment by akshayka** [comment] 2019-06-01 18:36
The previously mentioned commit, coupled with 0945cfc5af76a2a919f1aea954a6d777faa45ea9, fixed the issue. We were using an invalid API endpoint to fetch the JSON.

**Comment by akshayka** [comment] 2019-06-02 07:48
@rileyjmurray , I reverted 0945cfc. Reverting that commit breaks Travis deployment (as expected). We might need different server environment variables for getting the version info and for uploading the source distribution (because the JSON API endpoint is different, as far as I can tell, from the URL used for deployment), meaning we might need to slightly refactor the deployment script.

**Comment by SteveDiamond** [comment] 2019-06-02 18:37
What's the status of all this? I made sure both Travis and Appveyor have the environment variable ``PYPI_SERVER=https://upload.pypi.org/legacy/`` as discussed in the PR. I may have set Travis wrong before.

**Comment by rileyjmurray** [comment] 2019-06-02 18:56
@SteveDiamond The mistake (which URL to use) may have been on my part. I will look into this in more detail this week. I’m currently traveling so I can’t sit down in front of a computer and really do this now.

For the time being, @akshayka s now-reverted commit did successfully build and upload a source distribution to pypi. So from an end-user perspective, everything should be working normally. As long as we get this fixed before the next time you “bump” a cvxpy version, users should not be affected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akshayka** [comment] 2019-06-03 04:27
PYPI_SERVER is used in both deploying (`continuous_integration/Travis/deploy_script.sh`) and in fetching PyPi metadata (`continuous_integration/versiongetter.py`). It is currently set to `https://upload.pypi.org/legacy/`. This works for deploying / uploading to PyPi. It doesn't work for getting the package metadata, which needs to be retrieved from `https://pypi.python.org/pypi`.

We'd like to keep the function `pypi_version` from `versiongetter.py` parameterized by an environment variable, so that Riley and others can test Travis/Appveyor on test servers.

One fix would to have two separate variables --- PYPI_SERVER and PYPI_API_ENDPOINT, or something like that. Alternatively, we might be able to use `pypi.org` for both uploading (https://packaging.python.org/guides/migrating-to-pypi-org/) and getting metadata (`https://warehouse.pypa.io/api-reference/json/`), but I'm not sure.

**Comment by SteveDiamond** [comment] 2019-06-03 04:37
I added a PYPI_API_ENDPOINT variable to Travis and Appveyor, equal to ``https://pypi.python.org/pypi``.

**Comment by SteveDiamond** [comment] 2019-07-01 01:12
Checking back in, what's the status here?

**Comment by akshayka** [comment] 2019-07-01 03:40
Reopening — I don’t think this is fixed yet (or at least I haven’t fixed it yet). (If it’s fixed, then sorry!)

**Comment by rileyjmurray** [comment] 2019-07-01 03:41
Sorry guys I've been swamped. I have a paper going up on arXiv tonight (should be announced tomorrow). This is not fixed yet.

I would work on fixing this right now, but it looks like the AppVeyor builds are failing for an insane reason relating to anaconda. I kind of want to fix that issue first. (I've already got my fork back in sync with master, so I am actively working on it.)

**Comment by rileyjmurray** [comment] 2019-07-01 03:56
@akshayka if you can check my PR (and possibly merge) that would be appreciated. I could then turn to the issue in this thread.

**Comment by akshayka** [comment] 2019-07-01 04:16
No worries Riley -- congrats on the paper!

I just merged your PR. Thanks for submitting it!

**Comment by rileyjmurray** [comment] 2019-07-02 03:48
I spent a few hours on this today. The issues with PYPI_SERVER vs the new PYPI_API_ENDPOINT were easy to resolve.  I was also hoping to get manylinux wheels working, but it turns out those are more complicated than normal wheels.

At the very least I need to get OSX and Windows wheels for all versions of Python we support. If I made a PR with my current changes, we would only get wheels for Python 3.6. It turns out that in the deployment step, conda is forcing the Python version to 3.6 (even if we start the environment as 3.5, or 3.7). In order to fix this I will have to change most installation processes to not rely on conda (i.e. all dependencies will have to be resolved via a pip install).

I will take another stab at this tomorrow. Hopefully the changes to pip won't have that many complications.

**Comment by rileyjmurray** [comment] 2019-07-02 20:03
At the end of my lunch break it occurred to me that I could google how to override conda's update behavior for certain dependencies.

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning

Posting that link so I don't have to find it later tonight.

**Closed** 2019-07-08 18:32 UTC
