### ISSUE TITLE
ValueError: No updatable data has been specified! after fresh installation

### ISSUE THREAD

**Issue by jpiabrantes** [cvxgrp/cvxpy#615] opened 2018-10-24 12:27 UTC
Just installed cvxpy following the instructions on the website:
```sh
conda install -c conda-forge lapack
conda install -c cvxgrp cvxpy
```

And it failed the `nosetests`. I am using Ubuntu on Windows (WSL) version 18.04

 ```sh
>> nosetests cvxpy
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/expressions/expression.py:389: UserWarning: Forming a nonconvex expression.
  warnings.warn("Forming a nonconvex expression.")
........................................................................................................................................E......................................................
======================================================================
ERROR: Test warm start.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/tests/test_qp.py", line 388, in test_warm_start
    result2 = prob.solve(warm_start=True)
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 246, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 360, in _solve
    kwargs)
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 233, in solve_via_data
    solver_opts, problem._solver_cache)
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py", line 97, in solve_via_data
    solver.update(**new_args)
  File "/home/jpiabrantes/anaconda3/envs/optimal_env/lib/python3.6/site-packages/osqp/interface.py", line 218, in update
    raise ValueError("No updatable data has been specified!")
ValueError: No updatable data has been specified!

----------------------------------------------------------------------
Ran 1819 tests in 16.403s

FAILED (errors=1)
```

**Comment by bstellato** [comment] 2018-10-24 14:45
This error appears because the appveyor build keeps on failing and the newer cvxpy version has not been updated on windows. 

@rileyjmurray @SteveDiamond  this is related to lapack not being detected by SCS: https://ci.appveyor.com/project/StevenDiamond/cvxpy/build/job/03p6aylqnaplirsj#L1623

**Comment by rileyjmurray** [comment] 2018-10-29 17:13
The last successful [AppVeyor build](https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/18617373/job/yyxprobt10tgtw5t) shows that we installed ``mkl-2018.0.3``. The first build to [fail](https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/18966313/job/roqmhnqj8d0saylm) (due to SCS not linking into BLAS / LAPACK) says that ``mkl-2019`` was installed instead. I looked at the console messages when SCS was installed in each of these cases. In the working build, there are libraries named ``mkl_rt`` identified in ``C:/conda/envs/testenv\\Library\\lib`` (Line 1343). In the broken build there are no such libraries found (Lines 1342 to 1355).

I believe the issue can be resolved by requiring that mkl-2018.0.3 be installed (rather than mkl-2019). This can be accomplished by editing
https://github.com/cvxgrp/cvxpy/blob/b6d6b1370f367c26b9aa1ca375a900403571e183/continuous_integration/appveyor_install.ps1#L23
to have ``mkl=2018.0.3``. 

@SteveDiamond I don't have access to a widows machine at the moment. Can you make the above 1-line change to the master branch? That will trigger another AppVeyor build that will tell us if that solved the problem. (Note: if the proposed 1-line change to master doesn't fix it right away, I will setup another windows machine and do more serious debugging on my fork. I would just rather avoid that unless it's really necessary.)

**Comment by SteveDiamond** [comment] 2018-10-29 17:29
Thanks! I made the change. We'll see what happens.

**Comment by SteveDiamond** [comment] 2018-10-29 18:28
Could we update the conda and pip distributions after successful appveyor builds? I think @bstellato is right that the Windows binaries are out of date.

**Comment by rileyjmurray** [comment] 2018-10-29 19:25
What I was trying to say is that Windows binaries do not exist / have never existed; Windows users have needed to install from a source distribution hosted on pypi. To trigger a deployment of a new cvxpy source distribution (which hasn't happened since October 16th), you need to bump the version number (from 1.0.10 to 1.0.11).

As for getting Windows binaries in the future- a pretty good solution seems to be to rely on [Christoph Gohlke's unofficial builds](https://www.lfd.uci.edu/~gohlke/pythonlibs/). From what I understand they watch for updates to cvxpy's pypi source distribution and upload new builds automatically.

**Comment by bstellato** [comment] 2018-10-29 19:40
Windows binaries on conda have existed: https://anaconda.org/cvxgrp/cvxpy/files

Regarding pypi you can upload windows and osx binaries. However linux binaries are still not supported because many linux distributions can have different system folders. There are the manylinux pip binaries https://www.python.org/dev/peps/pep-0513/ that are recognized officially by the python foundation. You can use https://github.com/matthew-brett/multibuild to create them. This simplifies many problems with the installation because of the different virtual environments the users canm have.

After issue https://github.com/cvxgrp/cvxpy/issues/503 we decided to create the pypi packages for osqp always with multibuild to avoid installation errors. You can find the implementation here https://github.com/oxfordcontrol/osqp-wheels Multibuild is also used in numpy, scipy, astropy, etc.

It takes a bit of time to set it up at the beginning though but I believe it is a pretty good solution  in the long run.

**Comment by rileyjmurray** [comment] 2018-10-29 19:47
@bstellato I misspoke. Windows binaries have not existed for cvxpy since version 0.4.x. As a result- "out of date Windows binaries" should not be the cause of this user's error (assuming they are running cvxpy 1.x).

**Comment by biosopher** [comment] 2018-11-02 18:34
Still seeing this error.  Can we push this fix live...if it works?

**Comment by rileyjmurray** [comment] 2018-11-07 00:56
@biosopher the source of the error has not been identified. There is some back-and-forth about having binaries for Windows (as opposed to source distributions), but that does not apply to OSX machines.

**Comment by sz144** [comment] 2018-12-18 15:11
I have the same error reported on Ubuntu 16.04 for cvxpy 1.0.6.

**Comment by SteveDiamond** [comment] 2019-02-21 19:52
Any more thoughts on making Windows conda packages automatically? I'm trying to clean up the issues.

**Comment by rileyjmurray** [comment] 2019-02-21 20:47
This is something that I'll be able to work on in the next couple of weeks. (I'll mostly be writing up a paper so some coding will provide a nice way to take breaks from that.)

**Comment by SteveDiamond** [comment] 2019-02-21 23:15
Ok I see there's another issue about Windows conda packages. I'm going to close this. There have been a lot of changes to installation since. If anyone gets the error again, reopen it.

**Closed by SteveDiamond** 2019-02-21 23:15 UTC
