### ISSUE TITLE
Multithreaded call to ECOS fails with segmentation fault

### ISSUE THREAD

**Issue by behdad84** [cvxgrp/cvxpy#220] opened 2015-08-20 23:03 UTC
I am making calls to ECOS from every thread in a multithreaded program. The program fails with error 139 which I think means segmentation fault. Do you have any idea why this is happening? Thanks.

**Comment by SteveDiamond** [comment] 2015-08-20 23:39
Are you calling ecos directly or through cvxpy? Do you get a segmentation fault if you run the program with a single thread?

**Comment by behdad84** [comment] 2015-08-20 23:50
yes. I run the code through cvxpy. And no, when I run in one single thread it goes on fine!

**Comment by behdad84** [comment] 2015-08-25 17:38
In fact calling SCS (through cvxpy) is also facing the same problem (error 139) but more rarely. So the problem seems to be from cvxpy.

**Comment by SteveDiamond** [comment] 2015-08-26 07:06
Do you have code I can run that causes this error?

**Comment by behdad84** [comment] 2015-08-26 08:33
import threading
import cvxpy as cvx

def train():
    train_data = [0.1, 0.2, 0.15, 0.1, 0.2, 0.12]
    n = len(train_data)
    W1 = cvx.Variable(n, 1)
    obj = cvx.Minimize(0.5 * cvx.sum_entries(cvx.huber(train_data - W1, M=0.015)))
    prob = cvx.Problem(obj)
    prob.solve(solver=cvx.ECOS, verbose=False, max_iters=100)

thread_list = []
for i in range(1, 30):
    t = threading.Thread(target=train)
    thread_list.append(t)

for thread in thread_list:
    thread.start()

for thread in thread_list:
    thread.join()

print "Done"


Notes: 
1. When the number of threads is small, i.e., it is smaller than 2-3 the crash rarely happens. But when it increases it happens very often   
2. Changing the solver to "SCS" also causes the same problem.

**Comment by SteveDiamond** [comment] 2015-09-01 03:57
It works for me when I use the solvers CVXOPT, MOSEK, or GUROBI. It also works when I form the problem data for ECOS but don't call the solver. It only crashes when I call the ECOS solver. Here's an example:

```
import cvxpy as cvx
import threading
import ecos

def train():
    train_data = [0.1, 0.2, 0.15, 0.1, 0.2, 0.12]
    n = len(train_data)
    W1 = cvx.Variable(n, 1)
    obj = cvx.Minimize(0.5 * cvx.sum_entries(cvx.huber(train_data - W1, M=0.015)))
    prob = cvx.Problem(obj)
    # prob.solve(solver=cvx.GUROBI, verbose=False)
    # Get ECOS arguments.
    data = prob.get_problem_data(cvx.ECOS)
    # Call ECOS solver.
    # Works without this line, fails with this line.
    solver_output = ecos.solve(data["c"], data["G"], data["h"],
                               data["dims"], data["A"], data["b"])

thread_list = []
for i in range(1, 30):
    t = threading.Thread(target=train)
    thread_list.append(t)

for thread in thread_list:
    thread.start()

for thread in thread_list:
    thread.join()
```

I suggest starting an issue on ECOS.

**Comment by behdad84** [comment] 2015-09-01 17:36
That's right. I actually started started an issue in ECOS.

For now I am getting around the problem by locking the solve process so only one thread can enter. 

   from threading import Thread, Lock
   .....
    
    mutex.acquire()
    prob.solve(solver=cvx.ECOS, verbose=False, max_iters=100)
    mutex.release()

**Comment by SteveDiamond** [comment] 2015-09-01 18:33
I'm going to close this issue since the problem is in ECOS and SCS.

**Closed by SteveDiamond** 2015-09-01 18:33 UTC

**Comment by behdad84** [comment] 2015-09-11 18:04
Looks like ECOS has resolved the issue. https://github.com/cvxgrp/cvxpy/issues/220
As I am not sure if cvxpy installer build ECOS from source or not, can you please include the ECOS fixed version?
Thanks.

**Comment by SteveDiamond** [comment] 2015-09-11 19:16
Ok, I bumped the required ECOS version.
