### ISSUE TITLE
AttributeError: 'Task' object has no attribute '_Task__library'

### ISSUE THREAD

**Issue by shokirovnozir** [cvxgrp/cvxpy#500] opened 2018-05-25 12:03 UTC
Hi, 

After solving an optimal power flow problem I get the following error, 
Could help me in fixing this, (I am using CVXPY + MOSEK). Thanks.
```
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 984             
  Cones                  : 0               
  Scalar variables       : 141             
  Matrix variables       : 6               
  Integer variables      : 0               

Optimizer started.
GP based matrix reordering started.
GP based matrix reordering terminated.
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 984             
  Cones                  : 0               
  Scalar variables       : 141             
  Matrix variables       : 6               
  Integer variables      : 0               

Optimizer  - threads                : 4               
Optimizer  - solved problem         : the primal      
Optimizer  - Constraints            : 876
Optimizer  - Cones                  : 1
Optimizer  - Scalar variables       : 40                conic                  : 31              
Optimizer  - Semi-definite variables: 6                 scalarized             : 468             
Factor     - setup time             : 0.05              dense det. time        : 0.01            
Factor     - ML order time          : 0.01              GP order time          : 0.02            
Factor     - nonzeros before factor : 7.30e+04          after factor           : 2.41e+05        
Factor     - dense dim.             : 2                 flops                  : 8.53e+07        
Factor     - GP saved nzs           : 2608              GP saved flops         : 1.35e+06        
ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME  
0   1.8e+00  6.4e+00  1.0e+00  0.00e+00   9.529630469e+00   9.529630469e+00   1.0e+00  0.06  
1   1.8e-01  6.4e-01  9.2e-02  1.45e+00   1.237231359e+00   5.351471555e+00   1.0e-01  0.16  
2   3.6e-02  1.3e-01  7.0e-02  6.35e-01   4.210277235e-01   6.378552349e-01   2.0e-02  0.19  
3   7.5e-03  2.7e-02  8.1e-02  2.00e+00   5.839043985e-01   5.815552570e-01   4.3e-03  0.22  
4   1.6e-03  5.7e-03  3.7e-02  1.95e+00   6.007155404e-01   6.011208034e-01   8.9e-04  0.24  
5   4.2e-04  1.5e-03  2.1e-02  1.06e+00   5.641116848e-01   5.641312124e-01   2.4e-04  0.26  
6   9.5e-07  3.4e-06  1.2e-03  1.02e+00   5.600637417e-01   5.600634288e-01   5.4e-07  0.29  
7   2.4e-11  8.7e-11  1.4e-11  1.00e+00   5.600531912e-01   5.600531912e-01   1.4e-11  0.32  
Optimizer terminated. Time: 0.34    


Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: 5.6005319117e-01    nrm: 1e+00    Viol.  con: 1e-10    var: 0e+00    barvar: 0e+00  
  Dual.    obj: 5.6005319109e-01    nrm: 3e+00    Viol.  con: 0e+00    var: 6e-12    barvar: 1e-11  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-1c16f458ffbc> in <module>()
     74 # Form and solve problem
     75 prob = Problem(obj, constraints)
---> 76 prob.solve(solver = MOSEK, verbose = True)
     77 

~/cvxpy/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    244         else:
    245             solve_func = Problem._solve
--> 246         return solve_func(self, *args, **kwargs)
    247 
    248     @classmethod

~/cvxpy/cvxpy/problems/problem.py in _solve(self, solver, ignore_dcp, warm_start, verbose, parallel, **kwargs)
    359         solution = self._solving_chain.solve_via_data(self, data, warm_start, verbose,
    360                                                       kwargs)
--> 361         self.unpack_results(solution, self._solving_chain, inverse_data)
    362         return self.value
    363 

~/cvxpy/cvxpy/problems/problem.py in unpack_results(self, solution, chain, inverse_data)
    451             The inverse data returned by applying the chain to the problem.
    452         """
--> 453         solution = chain.invert(solution, inverse_data)
    454         self._value = solution.opt_val
    455         if solution.status in s.SOLUTION_PRESENT:

~/cvxpy/cvxpy/reductions/chain.py in invert(self, solution, inverse_data)
     64         """
     65         for r, inv in reversed(list(zip(self.reductions, inverse_data))):
---> 66             solution = r.invert(solution, inv)
     67         return solution

~/cvxpy/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py in invert(self, results, inverse_data)
    458             sol = mosek.soltype.itr  # the solution found via interior point method
    459 
--> 460         task.getprosta(sol)  # mosek "problem status"; unused.
    461         solution_status = task.getsolsta(sol)
    462 

~/.local/lib/python3.6/site-packages/mosek/__init__.py in accept(*args)
    123                 raise TypeError('Expected %d argument(s) (%d given)' % (len(argtlst), len(args)))
    124             try:
--> 125                 return fun(*[ t(a) for (t,a) in zip(argtlst,args) ])
    126             except TypeAcceptError as e:
    127                 raise TypeError(e)

~/.local/lib/python3.6/site-packages/mosek/__init__.py in getprosta(self, whichsol_)
   4958     res = __library__.MSK_XX_getprosta(self.__nativep,whichsol_,ctypes.byref(prosta_))
   4959     if res != 0:
-> 4960       result,msg = self.__getlasterror(res)
   4961       raise Error(rescode(res),Env.getcodedesc(rescode(res))[1])
   4962     _prosta_return_value = prosta(prosta_.value)

~/.local/lib/python3.6/site-packages/mosek/__init__.py in __getlasterror(self, res)
   2085       msglen = ctypes.c_int64(1024)
   2086       lasterr = ctypes.c_int()
-> 2087       r = self.__library.MSK_XX_getlasterror64(self.__nativep, ctypes.byref(lasterr), 0, ctypes.byref(msglen),None)
   2088       if r == 0:
   2089           #msg = (ctypes.c_char * (msglen.value+1))()

AttributeError: 'Task' object has no attribute '_Task__library'```

**Comment by aszekMosek** [comment] 2018-05-25 12:18
This will be a duplicate of #497

**Comment by shokirovnozir** [comment] 2018-05-25 13:40
I see, would going back to older cvxpy (0.4.9) solve the issue ?

**Comment by rileyjmurray** [comment] 2018-05-25 16:21
This will be fixed today.

However, until the fix is made, please use SCS (it's only a first order solver, so you'll need to provide the keyword argument "eps=1e-8" to get any decent precision).

**Comment by shokirovnozir** [comment] 2018-05-25 23:28
Thanks I made the appropriate changes, I guess, however still get these errors and the error code changes from run to run
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-1c16f458ffbc> in <module>()
     74 # Form and solve problem
     75 prob = Problem(obj, constraints)
---> 76 prob.solve(solver = MOSEK, verbose = True)
     77 

~/cvxpy/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    244         else:
    245             solve_func = Problem._solve
--> 246         return solve_func(self, *args, **kwargs)
    247 
    248     @classmethod

~/cvxpy/cvxpy/problems/problem.py in _solve(self, solver, ignore_dcp, warm_start, verbose, parallel, **kwargs)
    359         solution = self._solving_chain.solve_via_data(self, data, warm_start, verbose,
    360                                                       kwargs)
--> 361         self.unpack_results(solution, self._solving_chain, inverse_data)
    362         return self.value
    363 

~/cvxpy/cvxpy/problems/problem.py in unpack_results(self, solution, chain, inverse_data)
    451             The inverse data returned by applying the chain to the problem.
    452         """
--> 453         solution = chain.invert(solution, inverse_data)
    454         self._value = solution.opt_val
    455         if solution.status in s.SOLUTION_PRESENT:

~/cvxpy/cvxpy/reductions/chain.py in invert(self, solution, inverse_data)
     64         """
     65         for r, inv in reversed(list(zip(self.reductions, inverse_data))):
---> 66             solution = r.invert(solution, inv)
     67         return solution

~/cvxpy/cvxpy/reductions/complex2real/complex2real.py in invert(self, solution, inverse_data)
     85                     imag_id = inverse_data.real2imag[cid]
     86                     dvars[cid] = solution.dual_vars[cid] + \
---> 87                         1j*solution.dual_vars[imag_id]
     88         return Solution(solution.status, solution.opt_val, pvars, dvars,
     89                         solution.attr)

KeyError: 1353
```
If necessary I can also paste the code which leads to the problem, I think this is more of cvxpy problem ?

**Comment by rileyjmurray** [comment] 2018-05-25 23:42
There are known issues with complex2real in cvxpy 1.0. See #481 .

If you can post your code that would be very helpful. If it's research code (i.e. you'd rather not post it publicly yet) then feel free to send it to me directly at rmurray@caltech.edu (either the files themselves, or a link to where the files are hosted).

**Comment by shokirovnozir** [comment] 2018-05-26 01:59
Yeah after you mentioned the issue is with the complex variables in cvxpy 1.0., I decided not to use it and define everything in terms of real variables and make the required changes in my problem. Although the number of variables increased, the error is gone now. Thanks for the help.

**Closed** 2018-05-26 15:50 UTC
