### ISSUE TITLE
Geometric programming exits with error

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#655] opened 2019-01-11 21:31 UTC
My geometric program tries to exit with a solution which looks like this:
```
Solution(status=solver_error, opt_val=None, primal_vars={}, dual_vars={}, attr={})
```

That optimum value of `None` causes an issue on [this line](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/dgp2dcp/dgp2dcp.py#L85):
```
solution.opt_val = np.exp(solution.opt_val)
```
because you can't take an `exp` of `None`.

I think the appropriate solution here is to check for an optimum value of `None` or `solver_error` and, if either of these is the case, to return the solution returned by `Canonicalization.invert` directly.

**Comment by akshayka** [comment] 2019-01-15 01:44
@r-barnes, thanks for reporting and triaging this issue. I've pushed a fix to master (d2a554338174071f89574525d39aeea18055011c), and we'll cut a new release soon. As such, I'm closing this issue. Please do re-open if the fix isn't adequate.

**Closed by akshayka** 2019-01-15 01:44 UTC

**Comment by r-barnes** [comment] 2019-01-18 14:38
@akshayka: The fix looks adequate at the code level.

Conceptually, I'm not sure I understand why this case arises.

The problem I've asked cvxpy to solve passes all the checks for a disciplined geometric program and cvxpy accepts the problem. My expectation is that if the program is DGP then cvxpy should always be able to find and return solution. Since it's returning `None`, that means that either I misunderstand and a solution isn't guaranteed or there's a problem elsewhere.

Could you clarify? If this is indicative of an error, I can submit that as a separate issue.

**Comment by r-barnes** [comment] 2019-01-18 14:58
Actually, it looks as though I'm running out of iterations (used `verbose=True`).

I may submit a separate issue suggesting that that be clarified.

**Comment by akshayka** [comment] 2019-01-18 17:34
As you’ve surmised, even if a program is DGP (or DCP), a solver may fail to
converge to a solution; this might happen for a number of reasons, for
example poor conditioning of the problem or because of a deficiency in the
solver itself. In such cases, you might try using a different solver (eg,
problem.solve(solver=cvxpy.ECOS)).

Because DGP is a new addition, it’s possible that the solver error is
related to a bug in CVXPY’s canonicalization of the problem; feel free to
file another issue with code that reproduces the solver error, and we can
take a look.
