### ISSUE TITLE
Failure to solve boolean vector problem

### ISSUE THREAD

**Issue by thomas-woodruff** [cvxgrp/cvxpy#1207] opened 2021-01-09 11:57 UTC
I've been having some trouble solving boolean vector problems. I'm currently using the GLPK_MI solver.

This is a trivial problem that illustrates the behaviour:
```
import cvxpy as cp
import numpy as np

b = np.array([1, 2, 3])
x = cp.Variable(3, boolean=True)
constraints = [np.ones(3) @ x == 1]
objective = cp.Maximize(b @ x)
prob = cp.Problem(objective, constraints)
prob.solve(solver='GLPK_MI')
```

The solution should be something like `x = [0, 0, 1]`. Instead an error is thrown:
```
---------------------------------------------------------------------------
SolverError                               Traceback (most recent call last)
<ipython-input-7-3a3d1a7a24fb> in <module>
      7 objective = cp.Maximize(b @ x)
      8 prob = cp.Problem(objective, constraints)
----> 9 prob.solve(solver='GLPK_MI')

~/code/footbot/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    394         else:
    395             solve_func = Problem._solve
--> 396         return solve_func(self, *args, **kwargs)
    397 
    398     @classmethod

~/code/footbot/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, gp, qcp, requires_grad, enforce_dpp, **kwargs)
    752         solution = solving_chain.solve_via_data(
    753             self, data, warm_start, verbose, kwargs)
--> 754         self.unpack_results(solution, solving_chain, inverse_data)
    755         return self.value
    756 

~/code/footbot/venv/lib/python3.7/site-packages/cvxpy/problems/problem.py in unpack_results(self, solution, chain, inverse_data)
   1066             raise error.SolverError(
   1067                     "Solver '%s' failed. " % chain.solver.name() +
-> 1068                     "Try another solver, or solve with verbose=True for more "
   1069                     "information.")
   1070         self.unpack(solution)

SolverError: Solver 'GLPK_MI' failed. Try another solver, or solve with verbose=True for more information.
```

- OS: macOS Catalina 10.15.4
- cvxopt==1.2.4
- cvxpy==1.0.25

I've also tried this with the most up-to-date versions of cvxpy and cvxopt.

Thanks in advance 👍

**Comment by rileyjmurray** [comment] 2021-01-09 12:38
This is a duplicate of #1112. GLPK requires at least one linear inequality constraint. Refer to the other GitHub issue discussion to see how you might reformulate the problem to involve at least one inequality.

**Closed by rileyjmurray** 2021-01-09 12:38 UTC

**Comment by thomas-woodruff** [comment] 2021-01-10 06:13
Excellent - thanks for your help 👍
