### ISSUE TITLE
Stop resetting warning filters

### ISSUE THREAD

**Issue by colinc719** [cvxgrp/cvxpy#1238] opened 2021-02-12 23:38 UTC
**Describe the bug**
Multiplying an expression has a path that will reset existing warning filters.

**To Reproduce**
```python
import warnings

import cvxpy


class MyWarning(Warning):
    pass


with warnings.catch_warnings():
    warnings.simplefilter("error", MyWarning)
    [1, 2, 3] * cvxpy.Variable(3)
    warnings.warn(MyWarning("my msg"))
```

**Expected behavior**
I would expect
```
MyWarning: my msg
```
to be raised
(which happens if you remove the `[1, 2, 3] * cvxpy.Variable(3)` line)

**Version**
 - CVXPY Version: 1.1.10

**Comment by rileyjmurray** [comment] 2021-02-12 23:56
I'm not sure if I follow your example. We reset the warning filters to ensure that users are alerted if there are unknown places in their codebase where matmul happens by ``*``. The idea is that running non-compliant code will indicate how many times the deprecated syntax is used (not just "whether or not the deprecated syntax is used somewhere").

However, it seems that by resetting filters with this purpose in mind, we're also resetting any filters a user might have set for other purposes. Is that correct?

**Comment by colinc719** [comment] 2021-02-13 00:13
Yeah, the biggest thing is that it's resetting filters that are completely unrelated to cvxpy.

But, I also don't think you should be resetting filters at all.  We actually came across this bug because we were trying to turn this warning into an error after fixing all cases in our codebase.  I think you should just respect user's warning filters.

**Comment by akshayka** [comment] 2021-02-13 00:16
Python3 docs say

>  Repetitions of a particular warning for the same source location are typically suppressed.

(https://docs.python.org/3/library/warnings.html).

So maybe the warning behavior will work as we intend it, even if CVXPY doesn't touch filters.

**Comment by akshayka** [comment] 2021-02-13 00:23
Sorry, accidentally hit the close button.

Riley, I misunderstood your comment. You'd like to raise a warning every time. In that case, can we just use an "always" filter, instead of resetting warnings.

**Comment by colinc719** [comment] 2021-02-13 00:35
I think those decisions about whether to warn every time or just once should be up to the user.  If they want to warn once, they can:
```python
# library code
def do_something_bad():
    warnings.warn(UserWarning("I did a bad thing"))



# user code
with warnings.catch_warnings():
    warnings.simplefilter("once", UserWarning)
    for _ in range(3):
        do_something_bad()
```
output:
```
<ipython-input-48-207c6614fee3>:2: UserWarning: I did a bad thing
  warnings.warn(UserWarning("I did a bad thing"))
```
if they want to warn every time, they can
```python
# library code
def do_something_bad():
    warnings.warn(UserWarning("I did a bad thing"))



# user code
with warnings.catch_warnings():
    warnings.simplefilter("always", UserWarning)
    for _ in range(3):
        do_something_bad()
```
output:
```
<ipython-input-50-72e26ea2985c>:2: UserWarning: I did a bad thing
  warnings.warn(UserWarning("I did a bad thing"))
<ipython-input-50-72e26ea2985c>:2: UserWarning: I did a bad thing
  warnings.warn(UserWarning("I did a bad thing"))
<ipython-input-50-72e26ea2985c>:2: UserWarning: I did a bad thing
  warnings.warn(UserWarning("I did a bad thing"))
```

or if they want to make the warning an error, they can
```python
# library code
def do_something_bad():
    warnings.warn(UserWarning("I did a bad thing"))



# user code
with warnings.catch_warnings():
    warnings.simplefilter("error", UserWarning)
    for _ in range(3):
        do_something_bad()
```

output:
```
---------------------------------------------------------------------------
UserWarning                               Traceback (most recent call last)
<ipython-input-52-8f3f6be83be1> in <module>
      6     warnings.simplefilter("error", UserWarning)
      7     for _ in range(3):
----> 8         do_something_bad()
      9

<ipython-input-52-8f3f6be83be1> in do_something_bad()
      1 def do_something_bad():
----> 2     warnings.warn(UserWarning("I did a bad thing"))
      3
      4
      5 with warnings.catch_warnings():

UserWarning: I did a bad thing
```

Library code isn't supposed to make those decisions for the user.

**Comment by akshayka** [comment] 2021-02-13 00:51
That sounds reasonable to me.

**Comment by rileyjmurray** [comment] 2021-02-13 03:42
@akshayka I don't support changing this behavior in the way of #1239. The side effect of resetting *other* warnings was not intended and should be fixed. However, I don't agree that we should feel bound by conventions that "library code shouldn't do X". If we have a compelling reason to do "X" and the side effects are localized, then "X" should be on the table.

It's getting late here on the east coast but I will follow up with a more detailed explanation tomorrow.

**Comment by rileyjmurray** [comment] 2021-02-13 03:46
@akshayka @colinc719 I should say that I'm not familiar with best practices for using python warnings. I will also look into this more before making a suggestion about how to proceed. (I'll start by looking at the comment https://github.com/cvxgrp/cvxpy/issues/1238#issuecomment-778529414 in more detail.)

**Comment by akshayka** [comment] 2021-02-13 03:55
Sure, I don't feel strongly besides not resetting warnings globally.

We can raise a DeprecationWarning instead of a UserWarning, to preserve the behavior you want. I believe DeprecationWarning's are not suppressed after first issue.

**Comment by SteveDiamond** [comment] 2021-02-13 05:13
I'm fine with whatever you guys decide.

**Comment by akshayka** [comment] 2021-02-13 16:32
@rileyjmurray , one option is

```python
# library code
def foo():
  with warnings.catch_warnings():
      warnings.simplefilter("always", UserWarning, append=True)
      warnings.warn("warning issued", UserWarning)
```

The `catch_warnings` context manager will restore the warnings filter upon exit (https://docs.python.org/3/library/warnings.html#warnings.catch_warnings). The `append=True` flag will insert our filter to the end of the warnings filter list, instead of the front. This will let users override this filter if they wish.

For example

```python
# user code
warnings.simplefilter("error", UserWarning)
foo()
```

will issue an error:

```
UserWarning                               Traceback (most recent call last)
<ipython-input-16-55bac1850734> in <module>
      2 with warnings.catch_warnings():
      3     warnings.simplefilter("always", UserWarning, append=True)
----> 4     warnings.warn("warning issued", UserWarning)
      5 

UserWarning: warning issued
```
@colinc719, can you comment on whether this solution would be problematic for your use case?

**Comment by rileyjmurray** [comment] 2021-02-14 01:18
@akshayka I'd suggest going one step farther. We can use the context manager and append the "always" rule, but instead of using the ``UserWarning`` class we create a trivial ``MatmulWarning`` class:
```
class MatmulWarning(Warning):
    """Warning raised for accessing matmul by the * operator.
    """
    pass
```
Then if someone wants to suppress that warning, their context manager needs to suppress either *all* warnings or explicitly suppress ``MatmulWarning``. This new warning class can just go in ``cvxpy/error.py``.

I've made the change on my local copy and written tests to confirm expected behavior. If we go with this plan then the effects to the warning filters will be localized (by the context manager) and it will be possible to override them, but you will have to be very explicit about that.

**Closed** 2021-02-16 01:47 UTC

**Comment by colinc719** [comment] 2021-02-16 15:00
Yeah, I think that solve the issue from our perspective.  Thanks for the fast turnaround!
